CREATE TABLE admission_form (
    child_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    parent_id INT,
    additional_parent_id INT,
    classId INT,
    care_provider_id INT,
    dentist_id INT,
    child_first_name VARCHAR(255),
    child_last_name VARCHAR(255),
    nick_name VARCHAR(255),
    dob DATE,
    primary_language VARCHAR(100),
    school_age_child_school VARCHAR(255),
    custody_papers_apply BOOLEAN,
    gender VARCHAR(10),
    special_diabilities VARCHAR(255),
    allergies_reaction VARCHAR(255),
    additional_info VARCHAR(255),
    medication VARCHAR(255),
    health_insurance VARCHAR(255),
    policy_number VARCHAR(255),
    emergency_medical_care VARCHAR(255),
    first_aid_procedures VARCHAR(255),
    above_info_is_correct BOOLEAN,
    physical_exam_last_date DATE,
    dental_exam_last_date DATE,
    allergies VARCHAR(255),
    asthma VARCHAR(255),
    bleeding_problems VARCHAR(255),
    diabetes VARCHAR(255),
    epilepsy VARCHAR(255),
    frequent_ear_infections VARCHAR(255),
    frequent_illnesses VARCHAR(255),
    hearing_problems VARCHAR(255),
    high_fevers VARCHAR(255),
    hospitalization VARCHAR(255),
    rheumatic_fever VARCHAR(255),
    seizures_convulsions VARCHAR(255),
    serious_injuries_accidents VARCHAR(255),
    surgeries VARCHAR(255),
    vision_problems VARCHAR(255),
    medical_other VARCHAR(255),
    illness_in_pregnancy VARCHAR(255),
    condition_of_newborn VARCHAR(255),
    duration_of_pregnancy VARCHAR(255),
    birth_weight_lbs VARCHAR(255),
    birth_weight_oz VARCHAR(255),
    complications VARCHAR(255),
    bottle_fed VARCHAR(255),
    breast_fed VARCHAR(255),
    other_siblings_name VARCHAR(255),
    other_siblings_age VARCHAR(255),
    fam_hist_allergies BOOLEAN,
    fam_hist_heart_problems BOOLEAN,
    fam_hist_tuberculosis BOOLEAN,
    fam_hist_asthma BOOLEAN,
    fam_hist_high_blood_pressure BOOLEAN,
    fam_hist_vision_problems BOOLEAN,
    fam_hist_diabetes BOOLEAN,
    fam_hist_hyperactivity BOOLEAN,
    fam_hist_epilepsy BOOLEAN,
    fam_hist_no_illness BOOLEAN,
    age_group_friends VARCHAR(255),
    neighborhood_friends VARCHAR(255),
    relationship_with_mom VARCHAR(255),
    relationship_with_dad VARCHAR(255),
    relationship_with_sib VARCHAR(255),
    relationship_extended_family VARCHAR(255),
    fears_conflicts VARCHAR(255),
    c_response_frustration VARCHAR(255),
    favorite_activities VARCHAR(255),
    last_five_years_moved BOOLEAN,
    things_used_home VARCHAR(255),
    hours_of_television_daily VARCHAR(255),
    language_at_home VARCHAR(100),
    changes_home_situation BOOLEAN,
    educational_expectations_of_child TEXT,
    fam_his_instructions BOOLEAN,
    immunization_instructions BOOLEAN,
    important_fam_members VARCHAR(255),
    fam_celebrations VARCHAR(255),
    childcare_before BOOLEAN,
    reason_for_childcare_before VARCHAR(255),
    what_child_interests VARCHAR(255),
    drop_off_time TIME,
    pick_up_time TIME,
    restricted_diet BOOLEAN,
    restricted_diet_reason VARCHAR(255),
    eat_own BOOLEAN,
    eat_own_reason VARCHAR(255),
    favorite_foods VARCHAR(255),
    rest_middle_day BOOLEAN,
    reason_rest_middle_day VARCHAR(255),
    rest_routine VARCHAR(255),
    toilet_trained BOOLEAN,
    reason_for_toilet_trained VARCHAR(255),
    existing_illness_allergy BOOLEAN,
    explain_illness_allergy VARCHAR(255),
    functioning_at_age BOOLEAN,
    explain_functioning_at_age VARCHAR(255),
    able_to_walk BOOLEAN,
    explain_able_to_walk VARCHAR(255),
    communicate_their_needs BOOLEAN,
    explain_communicate_their_needs VARCHAR(255),
    any_medication BOOLEAN,
    explain_for_any_medication VARCHAR(255),
    special_equipment BOOLEAN,
    explain_special_equipment VARCHAR(255),
    significant_periods BOOLEAN,
    explain_significant_periods VARCHAR(255),
    accommodations BOOLEAN,
    explain_for_accommodations VARCHAR(255),
    additional_information TEXT,
    child_info_is_correct BOOLEAN,
    child_pick_up_password VARCHAR(255),
    pick_up_password_form BOOLEAN,
    photo_video_permission_form TEXT,
    photo_permission_electronic BOOLEAN,
    photo_permission_post BOOLEAN,
    security_release_policy_form BOOLEAN,
    med_technicians_med_transportation_waiver VARCHAR(255),
    medical_transportation_waiver BOOLEAN,
    health_policies BOOLEAN,
    parent_sign_outside_waiver BOOLEAN,
    approve_social_media_post BOOLEAN,
    printed_social_media_post VARCHAR(255),
    social_media_post BOOLEAN,
    parent_sign VARCHAR(255),
    parent_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    admin_sign VARCHAR(255),
    admin_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (parent_id) REFERENCES parent_info(id),
    FOREIGN KEY (additional_parent_id) REFERENCES parent_info(id),
    FOREIGN KEY (classId) REFERENCES class_details(class_id),
    FOREIGN KEY (care_provider_id) REFERENCES care_provider(id),
    FOREIGN KEY (dentist_id) REFERENCES dentist(id)
);


-------------------- STORED PROCEDURE--------------------------- 

------------------CREATE------------------

DELIMITER //

CREATE PROCEDURE sp_create_admission_form (
    IN p_child_first_name VARCHAR(255),
    IN p_child_last_name VARCHAR(255),
    IN p_nick_name VARCHAR(255),
    IN p_dob DATE,
    IN p_primary_language VARCHAR(100),
    IN p_school_age_child_school VARCHAR(255),
    IN p_custody_papers_apply BOOLEAN,
    IN p_gender VARCHAR(10)
)
BEGIN
    INSERT INTO admission_form (
        child_first_name,
        child_last_name,
        nick_name,
        dob,
        primary_language,
        school_age_child_school,
        custody_papers_apply,
        gender
    ) VALUES (
        p_child_first_name,
        p_child_last_name,
        p_nick_name,
        p_dob,
        p_primary_language,
        p_school_age_child_school,
        p_custody_papers_apply,
        p_gender
    );
END //

DELIMITER ;


------------------ GET -------------------

DELIMITER //

CREATE PROCEDURE spGetAdmissionForm(
    IN p_childId INT
)
BEGIN
    SELECT * 
    FROM admission_form 
    WHERE child_id = p_childId AND is_active = TRUE;
END //

DELIMITER ;


------------------ GET ALL ---------------

DELIMITER //

CREATE PROCEDURE spGetAllAdmissionForms()
BEGIN
    SELECT * 
    FROM admission_form 
    WHERE is_active = TRUE;
END //

DELIMITER ;




------------------ UPDATE ---------------- 


DELIMITER //

CREATE PROCEDURE apCreateAdmissionForm(
    IN p_child_id INT,
    IN p_parent_id INT,
    IN p_additional_parent_id INT,
    IN p_classId INT,
    IN p_care_provider_id INT,
    IN p_dentist_id INT,
    IN p_child_first_name VARCHAR(255),
    IN p_child_last_name VARCHAR(255),
    IN p_nick_name VARCHAR(255),
    IN p_dob DATE,
    IN p_primary_language VARCHAR(100),
    IN p_school_age_child_school VARCHAR(255),
    IN p_custody_papers_apply BOOLEAN,
    IN p_gender VARCHAR(10),
    IN p_special_diabilities VARCHAR(255),
    IN p_allergies_reaction VARCHAR(255),
    IN p_additional_info VARCHAR(255),
    IN p_medication VARCHAR(255),
    IN p_health_insurance VARCHAR(255),
    IN p_policy_number VARCHAR(255),
    IN p_emergency_medical_care VARCHAR(255),
    IN p_first_aid_procedures VARCHAR(255),
    IN p_above_info_is_correct BOOLEAN,
    IN p_physical_exam_last_date DATE,
    IN p_dental_exam_last_date DATE,
    IN p_allergies VARCHAR(255),
    IN p_asthma VARCHAR(255),
    IN p_bleeding_problems VARCHAR(255),
    IN p_diabetes VARCHAR(255),
    IN p_epilepsy VARCHAR(255),
    IN p_frequent_ear_infections VARCHAR(255),
    IN p_frequent_illnesses VARCHAR(255),
    IN p_hearing_problems VARCHAR(255),
    IN p_high_fevers VARCHAR(255),
    IN p_hospitalization VARCHAR(255),
    IN p_rheumatic_fever VARCHAR(255),
    IN p_seizures_convulsions VARCHAR(255),
    IN p_serious_injuries_accidents VARCHAR(255),
    IN p_surgeries VARCHAR(255),
    IN p_vision_problems VARCHAR(255),
    IN p_medical_other VARCHAR(255),
    IN p_illness_in_pregnancy VARCHAR(255),
    IN p_condition_of_newborn VARCHAR(255),
    IN p_duration_of_pregnancy VARCHAR(255),
    IN p_birth_weight_lbs VARCHAR(255),
    IN p_birth_weight_oz VARCHAR(255),
    IN p_complications VARCHAR(255),
    IN p_bottle_fed VARCHAR(255),
    IN p_breast_fed VARCHAR(255),
    IN p_other_siblings_name VARCHAR(255),
    IN p_other_siblings_age VARCHAR(255),
    IN p_fam_hist_allergies BOOLEAN,
    IN p_fam_hist_heart_problems BOOLEAN,
    IN p_fam_hist_tuberculosis BOOLEAN,
    IN p_fam_hist_asthma BOOLEAN,
    IN p_fam_hist_high_blood_pressure BOOLEAN,
    IN p_fam_hist_vision_problems BOOLEAN,
    IN p_fam_hist_diabetes BOOLEAN,
    IN p_fam_hist_hyperactivity BOOLEAN,
    IN p_fam_hist_epilepsy BOOLEAN,
    IN p_fam_hist_no_illness BOOLEAN,
    IN p_age_group_friends VARCHAR(255),
    IN p_neighborhood_friends VARCHAR(255),
    IN p_relationship_with_mom VARCHAR(255),
    IN p_relationship_with_dad VARCHAR(255),
    IN p_relationship_with_sib VARCHAR(255),
    IN p_relationship_extended_family VARCHAR(255),
    IN p_fears_conflicts VARCHAR(255),
    IN p_c_response_frustration VARCHAR(255),
    IN p_favorite_activities VARCHAR(255),
    IN p_last_five_years_moved BOOLEAN,
    IN p_things_used_home VARCHAR(255),
    IN p_hours_of_television_daily VARCHAR(255),
    IN p_language_at_home VARCHAR(100),
    IN p_changes_home_situation BOOLEAN,
    IN p_educational_expectations_of_child TEXT,
    IN p_fam_his_instructions BOOLEAN,
    IN p_immunization_instructions BOOLEAN,
    IN p_important_fam_members VARCHAR(255),
    IN p_fam_celebrations VARCHAR(255),
    IN p_childcare_before BOOLEAN,
    IN p_reason_for_childcare_before VARCHAR(255),
    IN p_what_child_interests VARCHAR(255),
    IN p_drop_off_time TIME,
    IN p_pick_up_time TIME,
    IN p_restricted_diet BOOLEAN,
    IN p_restricted_diet_reason VARCHAR(255),
    IN p_eat_own BOOLEAN,
    IN p_eat_own_reason VARCHAR(255),
    IN p_favorite_foods VARCHAR(255),
    IN p_rest_middle_day BOOLEAN,
    IN p_reason_rest_middle_day VARCHAR(255),
    IN p_rest_routine VARCHAR(255),
    IN p_toilet_trained BOOLEAN,
    IN p_reason_for_toilet_trained VARCHAR(255),
    IN p_existing_illness_allergy BOOLEAN,
    IN p_explain_illness_allergy VARCHAR(255),
    IN p_functioning_at_age BOOLEAN,
    IN p_explain_functioning_at_age VARCHAR(255),
    IN p_able_to_walk BOOLEAN,
    IN p_explain_able_to_walk VARCHAR(255),
    IN p_communicate_their_needs BOOLEAN,
    IN p_explain_communicate_their_needs VARCHAR(255),
    IN p_any_medication BOOLEAN,
    IN p_explain_for_any_medication VARCHAR(255),
    IN p_special_equipment BOOLEAN,
    IN p_explain_special_equipment VARCHAR(255),
    IN p_significant_periods BOOLEAN,
    IN p_explain_significant_periods VARCHAR(255),
    IN p_accommodations BOOLEAN,
    IN p_explain_for_accommodations VARCHAR(255),
    IN p_additional_information TEXT,
    IN p_child_info_is_correct BOOLEAN,
    IN p_child_pick_up_password VARCHAR(255),
    IN p_pick_up_password_form BOOLEAN,
    IN p_photo_video_permission_form VARCHAR(255),
    IN p_photo_permission_electronic BOOLEAN,
    IN p_photo_permission_post BOOLEAN,
    IN p_security_release_policy_form BOOLEAN,
    IN p_med_technicians_med_transportation_waiver VARCHAR(255),
    IN p_medical_transportation_waiver BOOLEAN,
    IN p_health_policies BOOLEAN,
    IN p_parent_sign_outside_waiver BOOLEAN,
    IN p_approve_social_media_post BOOLEAN,
    IN p_printed_social_media_post VARCHAR(255),
    IN p_social_media_post BOOLEAN,
    IN p_parent_sign VARCHAR(255),
    IN p_admin_sign VARCHAR(255)
)
BEGIN
    INSERT INTO admission_form (
        child_id,
        parent_id,
        additional_parent_id,
        classId,
        care_provider_id,
        dentist_id,
        child_first_name,
        child_last_name,
        nick_name,
        dob,
        primary_language,
        school_age_child_school,
        custody_papers_apply,
        gender,
        special_diabilities,
        allergies_reaction,
        additional_info,
        medication,
        health_insurance,
        policy_number,
        emergency_medical_care,
        first_aid_procedures,
        above_info_is_correct,
        physical_exam_last_date,
        dental_exam_last_date,
        allergies,
        asthma,
        bleeding_problems,
        diabetes,
        epilepsy,
        frequent_ear_infections,
        frequent_illnesses,
        hearing_problems,
        high_fevers,
        hospitalization,
        rheumatic_fever,
        seizures_convulsions,
        serious_injuries_accidents,
        surgeries,
        vision_problems,
        medical_other,
        illness_in_pregnancy,
        condition_of_newborn,
        duration_of_pregnancy,
        birth_weight_lbs,
        birth_weight_oz,
        complications,
        bottle_fed,
        breast_fed,
        other_siblings_name,
        other_siblings_age,
        fam_hist_allergies,
        fam_hist_heart_problems,
        fam_hist_tuberculosis,
        fam_hist_asthma,
        fam_hist_high_blood_pressure,
        fam_hist_vision_problems,
        fam_hist_diabetes,
        fam_hist_hyperactivity,
        fam_hist_epilepsy,
        fam_hist_no_illness,
        age_group_friends,
        neighborhood_friends,
        relationship_with_mom,
        relationship_with_dad,
        relationship_with_sib,
        relationship_extended_family,
        fears_conflicts,
        c_response_frustration,
        favorite_activities,
        last_five_years_moved,
        things_used_home,
        hours_of_television_daily,
        language_at_home,
        changes_home_situation,
        educational_expectations_of_child,
        fam_his_instructions,
        immunization_instructions,
        important_fam_members,
        fam_celebrations,
        childcare_before,
        reason_for_childcare_before,
        what_child_interests,
        drop_off_time,
        pick_up_time,
        restricted_diet,
        restricted_diet_reason,
        eat_own,
        eat_own_reason,
        favorite_foods,
        rest_middle_day,
        reason_rest_middle_day,
        rest_routine,
        toilet_trained,
        reason_for_toilet_trained,
        existing_illness_allergy,
        explain_illness_allergy,
        functioning_at_age,
        explain_functioning_at_age,
        able_to_walk,
        explain_able_to_walk,
        communicate_their_needs,
        explain_communicate_their_needs,
        any_medication,
        explain_for_any_medication,
        special_equipment,
        explain_special_equipment,
        significant_periods,
        explain_significant_periods,
        accommodations,
        explain_for_accommodations,
        additional_information,
        child_info_is_correct,
        child_pick_up_password,
        pick_up_password_form,
        photo_video_permission_form,
        photo_permission_electronic,
        photo_permission_post,
        security_release_policy_form,
        med_technicians_med_transportation_waiver,
        medical_transportation_waiver,
        health_policies,
        parent_sign_outside_waiver,
        approve_social_media_post,
        printed_social_media_post,
        social_media_post,
        parent_sign,
        admin_sign
    )
    VALUES (
        p_child_id,
        p_parent_id,
        p_additional_parent_id,
        p_classId,
        p_care_provider_id,
        p_dentist_id,
        p_child_first_name,
        p_child_last_name,
        p_nick_name,
        p_dob,
        p_primary_language,
        p_school_age_child_school,
        p_custody_papers_apply,
        p_gender,
        p_special_diabilities,
        p_allergies_reaction,
        p_additional_info,
        p_medication,
        p_health_insurance,
        p_policy_number,
        p_emergency_medical_care,
        p_first_aid_procedures,
        p_above_info_is_correct,
        p_physical_exam_last_date,
        p_dental_exam_last_date,
        p_allergies,
        p_asthma,
        p_bleeding_problems,
        p_diabetes,
        p_epilepsy,
        p_frequent_ear_infections,
        p_frequent_illnesses,
        p_hearing_problems,
        p_high_fevers,
        p_hospitalization,
        p_rheumatic_fever,
        p_seizures_convulsions,
        p_serious_injuries_accidents,
        p_surgeries,
        p_vision_problems,
        p_medical_other,
        p_illness_in_pregnancy,
        p_condition_of_newborn,
        p_duration_of_pregnancy,
        p_birth_weight_lbs,
        p_birth_weight_oz,
        p_complications,
        p_bottle_fed,
        p_breast_fed,
        p_other_siblings_name,
        p_other_siblings_age,
        p_fam_hist_allergies,
        p_fam_hist_heart_problems,
        p_fam_hist_tuberculosis,
        p_fam_hist_asthma,
        p_fam_hist_high_blood_pressure,
        p_fam_hist_vision_problems,
        p_fam_hist_diabetes,
        p_fam_hist_hyperactivity,
        p_fam_hist_epilepsy,
        p_fam_hist_no_illness,
        p_age_group_friends,
        p_neighborhood_friends,
        p_relationship_with_mom,
        p_relationship_with_dad,
        p_relationship_with_sib,
        p_relationship_extended_family,
        p_fears_conflicts,
        p_c_response_frustration,
        p_favorite_activities,
        p_last_five_years_moved,
        p_things_used_home,
        p_hours_of_television_daily,
        p_language_at_home,
        p_changes_home_situation,
        p_educational_expectations_of_child,
        p_fam_his_instructions,
        p_immunization_instructions,
        p_important_fam_members,
        p_fam_celebrations,
        p_childcare_before,
        p_reason_for_childcare_before,
        p_what_child_interests,
        p_drop_off_time,
        p_pick_up_time,
        p_restricted_diet,
        p_restricted_diet_reason,
        p_eat_own,
        p_eat_own_reason,
        p_favorite_foods,
        p_rest_middle_day,
        p_reason_rest_middle_day,
        p_rest_routine,
        p_toilet_trained,
        p_reason_for_toilet_trained,
        p_existing_illness_allergy,
        p_explain_illness_allergy,
        p_functioning_at_age,
        p_explain_functioning_at_age,
        p_able_to_walk,
        p_explain_able_to_walk,
        p_communicate_their_needs,
        p_explain_communicate_their_needs,
        p_any_medication,
        p_explain_for_any_medication,
        p_special_equipment,
        p_explain_special_equipment,
        p_significant_periods,
        p_explain_significant_periods,
        p_accommodations,
        p_explain_for_accommodations,
        p_additional_information,
        p_child_info_is_correct,
        p_child_pick_up_password,
        p_pick_up_password_form,
        p_photo_video_permission_form,
        p_photo_permission_electronic,
        p_photo_permission_post,
        p_security_release_policy_form,
        p_med_technicians_med_transportation_waiver,
        p_medical_transportation_waiver,
        p_health_policies,
        p_parent_sign_outside_waiver,
        p_approve_social_media_post,
        p_printed_social_media_post,
        p_social_media_post,
        p_parent_sign,
        p_admin_sign
    );

    WHERE 
        child_id = p_child_id AND is_active = TRUE;
END //

DELIMITER ;



------------------ DELETE ---------------- 

DELIMITER //

CREATE PROCEDURE spDeleteAdmissionForm(
    IN p_childId INT
)
BEGIN
    UPDATE admission_form
    SET is_active = FALSE
    WHERE child_id = p_childId;
END //

DELIMITER ;




