
CREATE TABLE child_info (
    child_id INT PRIMARY KEY,
    parent_id INT,
    additional_parent_id INT,
    classId INT,
    care_provider_id INT,
    dentist_id INT,
    child_first_name VARCHAR(255),
    child_last_name VARCHAR(255),
    nick_name VARCHAR(255),
    dob DATE,
    primary_language VARCHAR(100),
    school_age_child_school VARCHAR(255),
    custody_papers_apply BOOLEAN,
    gender VARCHAR(10),
    special_diabilities BOOLEAN,
    allergies_reaction BOOLEAN,
    additional_info TEXT,
    medication VARCHAR(255),
    health_insurance VARCHAR(255),
    policy_number VARCHAR(50),
    emergency_medical_care VARCHAR(255),
    first_aid_procedures VARCHAR(255),
    physical_exam_last_date DATE,
    dental_exam_last_date DATE,
    allergies BOOLEAN,
    asthma BOOLEAN,
    bleeding_problems BOOLEAN,
    diabetes BOOLEAN,
    epilepsy BOOLEAN,
    frequent_ear_infections BOOLEAN,
    frequent_illnesses BOOLEAN,
    hearing_problems BOOLEAN,
    high_fevers BOOLEAN,
    hospitalization BOOLEAN,
    rheumatic_fever BOOLEAN,
    seizures_convulsions BOOLEAN,
    serious_injuries_accidents BOOLEAN,
    surgeries BOOLEAN,
    vision_problems BOOLEAN,
    medical_other TEXT,
    illness_in_pregnancy BOOLEAN,
    condition_of_newborn BOOLEAN,
    duration_of_pregnancy VARCHAR(50),
    birth_weight_lbs INT,
    birth_weight_oz INT,
    complications BOOLEAN,
    bottle_fed BOOLEAN,
    breast_fed BOOLEAN,
    fam_hist_allergies BOOLEAN,
    fam_hist_heart_problems BOOLEAN,
    fam_hist_tuberculosis BOOLEAN,
    fam_hist_asthma BOOLEAN,
    fam_hist_high_blood_pressure BOOLEAN,
    fam_hist_vision_problems BOOLEAN,
    fam_hist_diabetes BOOLEAN,
    fam_hist_hyperactivity BOOLEAN,
    fam_hist_epilepsy BOOLEAN,
    fam_hist_no_illness BOOLEAN,
    other_siblings_name VARCHAR(255),
    other_siblings_age VARCHAR(255),
    age_group_friends VARCHAR(50),
    neighborhood_friends VARCHAR(255),
    relationship_with_mom VARCHAR(255),
    relationship_with_dad VARCHAR(255),
    relationship_with_sib VARCHAR(255),
    relationship_extended_family VARCHAR(255),
    fears_conflicts VARCHAR(255),
    c_response_frustration VARCHAR(255),
    favorite_activities TEXT,
    last_five_years_moved BOOLEAN,
    things_used_home VARCHAR(255),
    hours_of_television_daily VARCHAR(255),
    language_at_home VARCHAR(100),
    changes_home_situation BOOLEAN,
    educational_expectations_of_child TEXT,
    important_fam_members VARCHAR(255),
    fam_celebrations VARCHAR(255),
    childcare_before VARCHAR(255),
    reason_for_childcare_before TEXT,
    what_child_interests TEXT,
    drop_off_time TIME,
    pick_up_time TIME,
    restricted_diet BOOLEAN,
    restricted_diet_reason TEXT,
    eat_own BOOLEAN,
    eat_own_reason TEXT,
    favorite_foods TEXT,
    rest_middle_day BOOLEAN,
    reason_rest_middle_day TEXT,
    rest_routine VARCHAR(255),
    toilet_trained BOOLEAN,
    reason_for_toilet_trained TEXT,
    existing_illness_allergy BOOLEAN,
    explain_illness_allergy TEXT,
    functioning_at_age VARCHAR(255),
    explain_functioning_at_age TEXT,
    able_to_walk BOOLEAN,
    explain_able_to_walk TEXT,
    communicate_their_needs BOOLEAN,
    explain_communicate_their_needs TEXT,
    any_medication BOOLEAN,
    explain_for_any_medication TEXT,
    special_equipment BOOLEAN,
    explain_special_equipment TEXT,
    significant_periods VARCHAR(255),
    explain_significant_periods TEXT,
    accommodations BOOLEAN,
    explain_for_accommodations TEXT,
    additional_information TEXT,
    child_info_is_correct BOOLEAN,
    above_nfo_is_correct BOOLEAN,
    immunization_instructions TEXT,
    profile_info TEXT,
    child_pick_up_password VARCHAR(255),
    pick_up_password_form VARCHAR(255),
    photo_video_permission_form BOOLEAN,
    photo_permission__electronic BOOLEAN,
    security_release_policy_form BOOLEAN,
    med_technicians_med_transportation_waiver BOOLEAN,
    medical_transportation_waiver BOOLEAN,
    health_policies BOOLEAN,
    parent_sign_outside_waiver BOOLEAN,
    approve_social_media_post BOOLEAN,
    printed_social_media_post BOOLEAN,
    social_media_post TEXT,
    bank_routing VARCHAR(255),
    bank_account VARCHAR(255),
    driver_license VARCHAR(255),
    state VARCHAR(255),
    myself VARCHAR(255),
    enrollment_name VARCHAR(255),
    point_one_field VARCHAR(255),
    point_two_init VARCHAR(255),
    point_three_ini VARCHAR(255),
    point_four_init VARCHAR(255),
    point_five_init VARCHAR(255),
    point_six_init VARCHAR(255),
    point_seven_init VARCHAR(255),
    point_eight_init VARCHAR(255),
    point_nine_init VARCHAR(255),
    point_ten_init VARCHAR(255),
    point_eleven_init VARCHAR(255),
    point_twelve_init VARCHAR(255),
    point_thirteen_init VARCHAR(255),
    point_fourteen_init VARCHAR(255),
    point_fifteen_initi VARCHAR(255),
    point_sixteen_init VARCHAR(255),
    point_seventeen_init VARCHAR(255),
    point_eighteen_init VARCHAR(255),
    start_date DATE,
    schedule_date DATE,
    full_day BOOLEAN,
    half_day BOOLEAN,
    Welcome_Goddard_Agmt BOOLEAN,
    Mission_Statement_Agmt BOOLEAN,
    General_Information_Agmt BOOLEAN,
    Statement_Confidentiality_Agmt BOOLEAN,
    Parent_Access_Agmt BOOLEAN,
    Release_Children_Agmt BOOLEAN,
    Registration_Fees_Agmt BOOLEAN,
    Outside_Engagements_Agmt BOOLEAN,
    Health_Policies_Agmt BOOLEAN,
    Medication_Procedures_Agmt BOOLEAN,
    Bring_school_Agmt BOOLEAN,
    Rest_Time_Agmt BOOLEAN,
    Training_Philosophy_Agmt BOOLEAN,
    Affiliation_Policy_Agmt BOOLEAN,
    Security_Issue_Agmt BOOLEAN,
    Expulsion_Policy_Agmt BOOLEAN,
    Addressing_Individual_Child_Agmt BOOLEAN,
    Finalword_Agmt BOOLEAN,
    
    FOREIGN KEY (parent_id) REFERENCES parent_info(id),
    FOREIGN KEY (additional_parent_id) REFERENCES parent_info(id),
    FOREIGN KEY (classId) REFERENCES classdetails(classId),
    FOREIGN KEY (care_provider_id) REFERENCES care_provider(id),
    FOREIGN KEY (dentist_id) REFERENCES dentist(id)
);


    # create delete call store procedure:
 DELIMITER //

CREATE PROCEDURE DeleteChildInfo (
    IN child_id_param INT
)
BEGIN
    DELETE FROM child_info
    WHERE child_id = child_id_param;
END //

DELIMITER ;


DELIMITER //

CREATE PROCEDURE InsertChildInfo(
	IN p_child_id INT,
    IN p_parent_id INT,
    IN p_additional_parent_id INT,
    IN p_classId INT,
    IN p_care_provider_id INT,
    IN p_dentist_id INT,
    IN p_child_first_name VARCHAR(255),
    IN p_child_last_name VARCHAR(255),
    IN p_nick_name VARCHAR(255),
    IN p_dob DATE,
    IN p_primary_language VARCHAR(100),
    IN p_school_age_child_school VARCHAR(255),
    IN p_custody_papers_apply BOOLEAN,
    IN p_gender VARCHAR(10),
    IN p_special_diabilities BOOLEAN,
    IN p_allergies_reaction BOOLEAN,
    IN p_additional_info TEXT,
    IN p_medication VARCHAR(255),
    IN p_health_insurance VARCHAR(255),
    IN p_policy_number VARCHAR(50),
    IN p_emergency_medical_care VARCHAR(255),
    IN p_first_aid_procedures VARCHAR(255),
    IN p_physical_exam_last_date DATE,
    IN p_dental_exam_last_date DATE,
    IN p_allergies BOOLEAN,
    IN p_asthma BOOLEAN,
    IN p_bleeding_problems BOOLEAN,
    IN p_diabetes BOOLEAN,
    IN p_epilepsy BOOLEAN,
    IN p_frequent_ear_infections BOOLEAN,
    IN p_frequent_illnesses BOOLEAN,
    IN p_hearing_problems BOOLEAN,
    IN p_high_fevers BOOLEAN,
    IN p_hospitalization BOOLEAN,
    IN p_rheumatic_fever BOOLEAN,
    IN p_seizures_convulsions BOOLEAN,
    IN p_serious_injuries_accidents BOOLEAN,
    IN p_surgeries BOOLEAN,
    IN p_vision_problems BOOLEAN,
    IN p_medical_other TEXT,
    IN p_illness_in_pregnancy BOOLEAN,
    IN p_condition_of_newborn BOOLEAN,
    IN p_duration_of_pregnancy VARCHAR(50),
    IN p_birth_weight_lbs INT,
    IN p_birth_weight_oz INT,
    IN p_complications BOOLEAN,
    IN p_bottle_fed BOOLEAN,
    IN p_breast_fed BOOLEAN,
    IN p_fam_hist_allergies BOOLEAN,
    IN p_fam_hist_heart_problems BOOLEAN,
    IN p_fam_hist_tuberculosis BOOLEAN,
    IN p_fam_hist_asthma BOOLEAN,
    IN p_fam_hist_high_blood_pressure BOOLEAN,
    IN p_fam_hist_vision_problems BOOLEAN,
    IN p_fam_hist_diabetes BOOLEAN,
    IN p_fam_hist_hyperactivity BOOLEAN,
    IN p_fam_hist_epilepsy BOOLEAN,
    IN p_fam_hist_no_illness BOOLEAN,
    IN p_other_siblings_name VARCHAR(255),
    IN p_other_siblings_age VARCHAR(255),
    IN p_age_group_friends VARCHAR(50),
    IN p_neighborhood_friends VARCHAR(255),
    IN p_relationship_with_mom VARCHAR(255),
    IN p_relationship_with_dad VARCHAR(255),
    IN p_relationship_with_sib VARCHAR(255),
    IN p_relationship_extended_family VARCHAR(255),
    IN p_fears_conflicts VARCHAR(255),
    IN p_c_response_frustration VARCHAR(255),
    IN p_favorite_activities TEXT,
    IN p_last_five_years_moved BOOLEAN,
    IN p_things_used_home VARCHAR(255),
    IN p_hours_of_television_daily VARCHAR(255),
    IN p_language_at_home VARCHAR(100),
    IN p_changes_home_situation BOOLEAN,
    IN p_educational_expectations_of_child TEXT,
    IN p_important_fam_members VARCHAR(255),
    IN p_fam_celebrations VARCHAR(255),
    IN p_childcare_before VARCHAR(255),
    IN p_reason_for_childcare_before TEXT,
    IN p_what_child_interests TEXT,
    IN p_drop_off_time TIME,
    IN p_pick_up_time TIME,
    IN p_restricted_diet BOOLEAN,
    IN p_restricted_diet_reason TEXT,
    IN p_eat_own BOOLEAN,
    IN p_eat_own_reason TEXT,
    IN p_favorite_foods TEXT,
    IN p_rest_middle_day BOOLEAN,
    IN p_reason_rest_middle_day TEXT,
    IN p_rest_routine VARCHAR(255),
    IN p_toilet_trained BOOLEAN,
    IN p_reason_for_toilet_trained TEXT,
    IN p_existing_illness_allergy BOOLEAN,
    IN p_explain_illness_allergy TEXT,
    IN p_functioning_at_age VARCHAR(255),
    IN p_explain_functioning_at_age TEXT,
    IN p_able_to_walk BOOLEAN,
    IN p_explain_able_to_walk TEXT,
    IN p_communicate_their_needs BOOLEAN,
    IN p_explain_communicate_their_needs TEXT,
    IN p_any_medication BOOLEAN,
    IN p_explain_for_any_medication TEXT,
    IN p_special_equipment BOOLEAN,
    IN p_explain_special_equipment TEXT,
    IN p_significant_periods VARCHAR(255),
    IN p_explain_significant_periods TEXT,
    IN p_accommodations BOOLEAN,
    IN p_explain_for_accommodations TEXT,
    IN p_additional_information TEXT,
    IN p_child_info_is_correct BOOLEAN,
    IN p_above_nfo_is_correct BOOLEAN,
    IN p_immunization_instructions TEXT,
    IN p_profile_info TEXT,
    IN p_child_pick_up_password VARCHAR(255),
    IN p_pick_up_password_form VARCHAR(255),
    IN p_photo_video_permission_form BOOLEAN,
    IN p_photo_permission__electronic BOOLEAN,
    IN p_security_release_policy_form BOOLEAN,
    IN p_med_technicians_med_transportation_waiver BOOLEAN,
    IN p_medical_transportation_waiver BOOLEAN,
    IN p_health_policies BOOLEAN,
    IN p_parent_sign_outside_waiver BOOLEAN,
    IN p_approve_social_media_post BOOLEAN,
    IN p_printed_social_media_post BOOLEAN,
    IN p_social_media_post TEXT,
    IN p_bank_routing VARCHAR(255),
    IN p_bank_account VARCHAR(255),
    IN p_driver_license VARCHAR(255),
    IN p_state VARCHAR(255),
    IN p_myself VARCHAR(255),
    IN p_enrollment_name VARCHAR(255),
    IN p_point_one_field VARCHAR(255),
    IN p_point_two_init VARCHAR(255),
    IN p_point_three_ini VARCHAR(255),
    IN p_point_four_init VARCHAR(255),
    IN p_point_five_init VARCHAR(255),
    IN p_point_six_init VARCHAR(255),
    IN p_point_seven_init VARCHAR(255),
    IN p_point_eight_init VARCHAR(255),
    IN p_point_nine_init VARCHAR(255),
    IN p_point_ten_init VARCHAR(255),
    IN p_point_eleven_init VARCHAR(255),
    IN p_point_twelve_init VARCHAR(255),
    IN p_point_thirteen_init VARCHAR(255),
    IN p_point_fourteen_init VARCHAR(255),
    IN p_point_fifteen_initi VARCHAR(255),
    IN p_point_sixteen_init VARCHAR(255),
    IN p_point_seventeen_init VARCHAR(255),
    IN p_point_eighteen_init VARCHAR(255),
    IN p_start_date DATE,
    IN p_schedule_date DATE,
    IN p_full_day BOOLEAN,
    IN p_half_day BOOLEAN,
    IN p_Welcome_Goddard_Agmt BOOLEAN,
    IN p_Mission_Statement_Agmt BOOLEAN,
    IN p_General_Information_Agmt BOOLEAN,
    IN p_Statement_Confidentiality_Agmt BOOLEAN,
    IN p_Parent_Access_Agmt BOOLEAN,
    IN p_Release_Children_Agmt BOOLEAN,
    IN p_Registration_Fees_Agmt BOOLEAN,
    IN p_Outside_Engagements_Agmt BOOLEAN,
    IN p_Health_Policies_Agmt BOOLEAN,
    IN p_Medication_Procedures_Agmt BOOLEAN,
    IN p_Bring_school_Agmt BOOLEAN,
    IN p_Rest_Time_Agmt BOOLEAN,
    IN p_Training_Philosophy_Agmt BOOLEAN,
    IN p_Affiliation_Policy_Agmt BOOLEAN,
    IN p_Security_Issue_Agmt BOOLEAN,
    IN p_Expulsion_Policy_Agmt BOOLEAN,
    IN p_Addressing_Individual_Child_Agmt BOOLEAN,
    IN p_Finalword_Agmt BOOLEAN
)
BEGIN
    INSERT INTO child_info (
		child_id,
        parent_id,
        additional_parent_id,
        classId,
        care_provider_id,
        dentist_id,
        child_first_name,
        child_last_name,
        nick_name,
        dob,
        primary_language,
        school_age_child_school,
        custody_papers_apply,
        gender,
        special_diabilities,
        allergies_reaction,
        additional_info,
        medication,
        health_insurance,
        policy_number,
        emergency_medical_care,
        first_aid_procedures,
        physical_exam_last_date,
        dental_exam_last_date,
        allergies,
        asthma,
        bleeding_problems,
        diabetes,
        epilepsy,
        frequent_ear_infections,
        frequent_illnesses,
        hearing_problems,
        high_fevers,
        hospitalization,
        rheumatic_fever,
        seizures_convulsions,
        serious_injuries_accidents,
        surgeries,
        vision_problems,
        medical_other,
        illness_in_pregnancy,
        condition_of_newborn,
        duration_of_pregnancy,
        birth_weight_lbs,
        birth_weight_oz,
        complications,
        bottle_fed,
        breast_fed,
        fam_hist_allergies,
        fam_hist_heart_problems,
        fam_hist_tuberculosis,
        fam_hist_asthma,
        fam_hist_high_blood_pressure,
        fam_hist_vision_problems,
        fam_hist_diabetes,
        fam_hist_hyperactivity,
        fam_hist_epilepsy,
        fam_hist_no_illness,
        other_siblings_name,
        other_siblings_age,
        age_group_friends,
        neighborhood_friends,
        relationship_with_mom,
        relationship_with_dad,
        relationship_with_sib,
        relationship_extended_family,
        fears_conflicts,
        c_response_frustration,
        favorite_activities,
        last_five_years_moved,
        things_used_home,
        hours_of_television_daily,
        language_at_home,
        changes_home_situation,
        educational_expectations_of_child,
        important_fam_members,
        fam_celebrations,
        childcare_before,
        reason_for_childcare_before,
        what_child_interests,
        drop_off_time,
        pick_up_time,
        restricted_diet,
        restricted_diet_reason,
        eat_own,
        eat_own_reason,
        favorite_foods,
        rest_middle_day,
        reason_rest_middle_day,
        rest_routine,
        toilet_trained,
        reason_for_toilet_trained,
        existing_illness_allergy,
        explain_illness_allergy,
        functioning_at_age,
        explain_functioning_at_age,
        able_to_walk,
        explain_able_to_walk,
        communicate_their_needs,
        explain_communicate_their_needs,
        any_medication,
        explain_for_any_medication,
        special_equipment,
        explain_special_equipment,
        significant_periods,
        explain_significant_periods,
        accommodations,
        explain_for_accommodations,
        additional_information,
        child_info_is_correct,
        above_nfo_is_correct,
        immunization_instructions,
        profile_info,
        child_pick_up_password,
        pick_up_password_form,
        photo_video_permission_form,
        photo_permission__electronic,
        security_release_policy_form,
        med_technicians_med_transportation_waiver,
        medical_transportation_waiver,
        health_policies,
        parent_sign_outside_waiver,
        approve_social_media_post,
        printed_social_media_post,
        social_media_post,
        bank_routing,
        bank_account,
        driver_license,
        state,
        myself,
        enrollment_name,
        point_one_field,
        point_two_init,
        point_three_ini,
        point_four_init,
        point_five_init,
        point_six_init,
        point_seven_init,
        point_eight_init,
        point_nine_init,
        point_ten_init,
        point_eleven_init,
        point_twelve_init,
        point_thirteen_init,
        point_fourteen_init,
        point_fifteen_initi,
        point_sixteen_init,
        point_seventeen_init,
        point_eighteen_init,
        start_date,
        schedule_date,
        full_day,
        half_day,
        Welcome_Goddard_Agmt,
        Mission_Statement_Agmt,
        General_Information_Agmt,
        Statement_Confidentiality_Agmt,
        Parent_Access_Agmt,
        Release_Children_Agmt,
        Registration_Fees_Agmt,
        Outside_Engagements_Agmt,
        Health_Policies_Agmt,
        Medication_Procedures_Agmt,
        Bring_school_Agmt,
        Rest_Time_Agmt,
        Training_Philosophy_Agmt,
        Affiliation_Policy_Agmt,
        Security_Issue_Agmt,
        Expulsion_Policy_Agmt,
        Addressing_Individual_Child_Agmt,
        Finalword_Agmt
    ) VALUES (
        p_parent_id,
        p_additional_parent_id,
        p_classId,
        p_care_provider_id,
        p_dentist_id,
        p_child_first_name,
        p_child_last_name,
        p_nick_name,
        p_dob,
        p_primary_language,
        p_school_age_child_school,
        p_custody_papers_apply,
        p_gender,
        p_special_diabilities,
        p_allergies_reaction,
        p_additional_info,
        p_medication,
        p_health_insurance,
        p_policy_number,
        p_emergency_medical_care,
        p_first_aid_procedures,
        p_physical_exam_last_date,
        p_dental_exam_last_date,
        p_allergies,
        p_asthma,
        p_bleeding_problems,
        p_diabetes,
        p_epilepsy,
        p_frequent_ear_infections,
        p_frequent_illnesses,
        p_hearing_problems,
        p_high_fevers,
        p_hospitalization,
        p_rheumatic_fever,
        p_seizures_convulsions,
        p_serious_injuries_accidents,
        p_surgeries,
        p_vision_problems,
        p_medical_other,
        p_illness_in_pregnancy,
        p_condition_of_newborn,
        p_duration_of_pregnancy,
        p_birth_weight_lbs,
        p_birth_weight_oz,
        p_complications,
        p_bottle_fed,
        p_breast_fed,
        p_fam_hist_allergies,
        p_fam_hist_heart_problems,
        p_fam_hist_tuberculosis,
        p_fam_hist_asthma,
        p_fam_hist_high_blood_pressure,
        p_fam_hist_vision_problems,
        p_fam_hist_diabetes,
        p_fam_hist_hyperactivity,
        p_fam_hist_epilepsy,
        p_fam_hist_no_illness,
        p_other_siblings_name,
        p_other_siblings_age,
        p_age_group_friends,
        p_neighborhood_friends,
        p_relationship_with_mom,
        p_relationship_with_dad,
        p_relationship_with_sib,
        p_relationship_extended_family,
        p_fears_conflicts,
        p_c_response_frustration,
        p_favorite_activities,
        p_last_five_years_moved,
        p_things_used_home,
        p_hours_of_television_daily,
        p_language_at_home,
        p_changes_home_situation,
        p_educational_expectations_of_child,
        p_important_fam_members,
        p_fam_celebrations,
        p_childcare_before,
        p_reason_for_childcare_before,
        p_what_child_interests,
        p_drop_off_time,
        p_pick_up_time,
        p_restricted_diet,
        p_restricted_diet_reason,
        p_eat_own,
        p_eat_own_reason,
        p_favorite_foods,
        p_rest_middle_day,
        p_reason_rest_middle_day,
        p_rest_routine,
        p_toilet_trained,
        p_reason_for_toilet_trained,
        p_existing_illness_allergy,
        p_explain_illness_allergy,
        p_functioning_at_age,
        p_explain_functioning_at_age,
        p_able_to_walk,
        p_explain_able_to_walk,
        p_communicate_their_needs,
        p_explain_communicate_their_needs,
        p_any_medication,
        p_explain_for_any_medication,
        p_special_equipment,
        p_explain_special_equipment,
        p_significant_periods,
        p_explain_significant_periods,
        p_accommodations,
        p_explain_for_accommodations,
        p_additional_information,
        p_child_info_is_correct,
        p_above_nfo_is_correct,
        p_immunization_instructions,
        p_profile_info,
        p_child_pick_up_password,
        p_pick_up_password_form,
        p_photo_video_permission_form,
        p_photo_permission__electronic,
        p_security_release_policy_form,
        p_med_technicians_med_transportation_waiver,
        p_medical_transportation_waiver,
        p_health_policies,
        p_parent_sign_outside_waiver,
        p_approve_social_media_post,
        p_printed_social_media_post,
        p_social_media_post,
        p_bank_routing,
        p_bank_account,
        p_driver_license,
        p_state,
        p_myself,
        p_enrollment_name,
        p_point_one_field,
        p_point_two_init,
        p_point_three_ini,
        p_point_four_init,
        p_point_five_init,
        p_point_six_init,
        p_point_seven_init,
        p_point_eight_init,
        p_point_nine_init,
        p_point_ten_init,
        p_point_eleven_init,
        p_point_twelve_init,
        p_point_thirteen_init,
        p_point_fourteen_init,
        p_point_fifteen_initi,
        p_point_sixteen_init,
        p_point_seventeen_init,
        p_point_eighteen_init,
        p_start_date,
        p_schedule_date,
        p_full_day,
        p_half_day,
        p_Welcome_Goddard_Agmt,
        p_Mission_Statement_Agmt,
        p_General_Information_Agmt,
        p_Statement_Confidentiality_Agmt,
        p_Parent_Access_Agmt,
        p_Release_Children_Agmt,
        p_Registration_Fees_Agmt,
        p_Outside_Engagements_Agmt,
        p_Health_Policies_Agmt,
        p_Medication_Procedures_Agmt,
        p_Bring_school_Agmt,
        p_Rest_Time_Agmt,
        p_Training_Philosophy_Agmt,
        p_Affiliation_Policy_Agmt,
        p_Security_Issue_Agmt,
        p_Expulsion_Policy_Agmt,
        p_Addressing_Individual_Child_Agmt,
        p_Finalword_Agmt
    );
END //

DELIMITER ;

 
 
#getbyid
 DELIMITER //

CREATE PROCEDURE get_child_info_by_id(
    IN p_child_id INT
)
BEGIN
    SELECT *
    FROM child_info
    WHERE child_id = p_child_id;
END //

DELIMITER ;

#getall

DELIMITER //

CREATE PROCEDURE get_all_child_info()
BEGIN
    SELECT * FROM child_info;
END //

DELIMITER ;

#update store procedure

DELIMITER //

CREATE PROCEDURE UpdateChildInfo(
    IN p_child_id INT,
    IN p_parent_id INT,
    IN p_additional_parent_id INT,
    IN p_classId INT,
    IN p_care_provider_id INT,
    IN p_dentist_id INT,
    IN p_child_first_name VARCHAR(255),
    IN p_child_last_name VARCHAR(255),
    IN p_nick_name VARCHAR(255),
    IN p_dob DATE,
    IN p_primary_language VARCHAR(100),
    IN p_school_age_child_school VARCHAR(255),
    IN p_custody_papers_apply BOOLEAN,
    IN p_gender VARCHAR(10),
    IN p_special_diabilities BOOLEAN,
    IN p_allergies_reaction BOOLEAN,
    IN p_additional_info TEXT,
    IN p_medication VARCHAR(255),
    IN p_health_insurance VARCHAR(255),
    IN p_policy_number VARCHAR(50),
    IN p_emergency_medical_care VARCHAR(255),
    IN p_first_aid_procedures VARCHAR(255),
    IN p_physical_exam_last_date DATE,
    IN p_dental_exam_last_date DATE,
    IN p_allergies BOOLEAN,
    IN p_asthma BOOLEAN,
    IN p_bleeding_problems BOOLEAN,
    IN p_diabetes BOOLEAN,
    IN p_epilepsy BOOLEAN,
    IN p_frequent_ear_infections BOOLEAN,
    IN p_frequent_illnesses BOOLEAN,
    IN p_hearing_problems BOOLEAN,
    IN p_high_fevers BOOLEAN,
    IN p_hospitalization BOOLEAN,
    IN p_rheumatic_fever BOOLEAN,
    IN p_seizures_convulsions BOOLEAN,
    IN p_serious_injuries_accidents BOOLEAN,
    IN p_surgeries BOOLEAN,
    IN p_vision_problems BOOLEAN,
    IN p_medical_other TEXT,
    IN p_illness_in_pregnancy BOOLEAN,
    IN p_condition_of_newborn BOOLEAN,
    IN p_duration_of_pregnancy VARCHAR(50),
    IN p_birth_weight_lbs INT,
    IN p_birth_weight_oz INT,
    IN p_complications BOOLEAN,
    IN p_bottle_fed BOOLEAN,
    IN p_breast_fed BOOLEAN,
    IN p_fam_hist_allergies BOOLEAN,
    IN p_fam_hist_heart_problems BOOLEAN,
    IN p_fam_hist_tuberculosis BOOLEAN,
    IN p_fam_hist_asthma BOOLEAN,
    IN p_fam_hist_high_blood_pressure BOOLEAN,
    IN p_fam_hist_vision_problems BOOLEAN,
    IN p_fam_hist_diabetes BOOLEAN,
    IN p_fam_hist_hyperactivity BOOLEAN,
    IN p_fam_hist_epilepsy BOOLEAN,
    IN p_fam_hist_no_illness BOOLEAN,
    IN p_other_siblings_name VARCHAR(255),
    IN p_other_siblings_age VARCHAR(255),
    IN p_age_group_friends VARCHAR(50),
    IN p_neighborhood_friends VARCHAR(255),
    IN p_relationship_with_mom VARCHAR(255),
    IN p_relationship_with_dad VARCHAR(255),
    IN p_relationship_with_sib VARCHAR(255),
    IN p_relationship_extended_family VARCHAR(255),
    IN p_fears_conflicts VARCHAR(255),
    IN p_c_response_frustration VARCHAR(255),
    IN p_favorite_activities TEXT,
    IN p_last_five_years_moved BOOLEAN,
    IN p_things_used_home VARCHAR(255),
    IN p_hours_of_television_daily VARCHAR(255),
    IN p_language_at_home VARCHAR(100),
    IN p_changes_home_situation BOOLEAN,
    IN p_educational_expectations_of_child TEXT,
    IN p_important_fam_members VARCHAR(255),
    IN p_fam_celebrations VARCHAR(255),
    IN p_childcare_before VARCHAR(255),
    IN p_reason_for_childcare_before TEXT,
    IN p_what_child_interests TEXT,
    IN p_drop_off_time TIME,
    IN p_pick_up_time TIME,
    IN p_restricted_diet BOOLEAN,
    IN p_restricted_diet_reason TEXT,
    IN p_eat_own BOOLEAN,
    IN p_eat_own_reason TEXT,
    IN p_favorite_foods TEXT,
    IN p_rest_middle_day BOOLEAN,
    IN p_reason_rest_middle_day TEXT,
    IN p_rest_routine VARCHAR(255),
    IN p_toilet_trained BOOLEAN,
    IN p_reason_for_toilet_trained TEXT,
    IN p_existing_illness_allergy BOOLEAN,
    IN p_explain_illness_allergy TEXT,
    IN p_functioning_at_age VARCHAR(255),
    IN p_explain_functioning_at_age TEXT,
    IN p_able_to_walk BOOLEAN,
    IN p_explain_able_to_walk TEXT,
    IN p_communicate_their_needs BOOLEAN,
    IN p_explain_communicate_their_needs TEXT,
    IN p_any_medication BOOLEAN,
    IN p_explain_for_any_medication TEXT,
    IN p_special_equipment BOOLEAN,
    IN p_explain_special_equipment TEXT,
    IN p_significant_periods VARCHAR(255),
    IN p_explain_significant_periods TEXT,
    IN p_accommodations BOOLEAN,
    IN p_explain_for_accommodations TEXT,
    IN p_additional_information TEXT,
    IN p_child_info_is_correct BOOLEAN,
    IN p_above_nfo_is_correct BOOLEAN,
    IN p_immunization_instructions TEXT,
    IN p_profile_info TEXT,
    IN p_child_pick_up_password VARCHAR(255),
    IN p_pick_up_password_form VARCHAR(255),
    IN p_photo_video_permission_form BOOLEAN,
    IN p_photo_permission__electronic BOOLEAN,
    IN p_security_release_policy_form BOOLEAN,
    IN p_med_technicians_med_transportation_waiver BOOLEAN,
    IN p_medical_transportation_waiver BOOLEAN,
    IN p_health_policies BOOLEAN,
    IN p_parent_sign_outside_waiver BOOLEAN,
    IN p_approve_social_media_post BOOLEAN,
    IN p_printed_social_media_post BOOLEAN,
    IN p_social_media_post TEXT,
    IN p_bank_routing VARCHAR(255),
    IN p_bank_account VARCHAR(255),
    IN p_driver_license VARCHAR(255),
    IN p_state VARCHAR(255),
    IN p_myself VARCHAR(255),
    IN p_enrollment_name VARCHAR(255),
    IN p_point_one_field VARCHAR(255),
    IN p_point_two_init VARCHAR(255),
    IN p_point_three_ini VARCHAR(255),
    IN p_point_four_init VARCHAR(255),
    IN p_point_five_init VARCHAR(255),
    IN p_point_six_init VARCHAR(255),
    IN p_point_seven_init VARCHAR(255),
    IN p_point_eight_init VARCHAR(255),
    IN p_point_nine_init VARCHAR(255),
    IN p_point_ten_init VARCHAR(255),
    IN p_point_eleven_init VARCHAR(255),
    IN p_point_twelve_init VARCHAR(255),
    IN p_point_thirteen_init VARCHAR(255),
    IN p_point_fourteen_init VARCHAR(255),
    IN p_point_fifteen_initi VARCHAR(255),
    IN p_point_sixteen_init VARCHAR(255),
    IN p_point_seventeen_init VARCHAR(255),
    IN p_point_eighteen_init VARCHAR(255),
    IN p_start_date DATE,
    IN p_schedule_date DATE,
    IN p_full_day BOOLEAN,
    IN p_half_day BOOLEAN,
    IN p_Welcome_Goddard_Agmt BOOLEAN,
    IN p_Mission_Statement_Agmt BOOLEAN,
    IN p_General_Information_Agmt BOOLEAN,
    IN p_Statement_Confidentiality_Agmt BOOLEAN,
    IN p_Parent_Access_Agmt BOOLEAN,
    IN p_Release_Children_Agmt BOOLEAN,
    IN p_Registration_Fees_Agmt BOOLEAN,
    IN p_Outside_Engagements_Agmt BOOLEAN,
    IN p_Health_Policies_Agmt BOOLEAN,
    IN p_Medication_Procedures_Agmt BOOLEAN,
    IN p_Bring_school_Agmt BOOLEAN,
    IN p_Rest_Time_Agmt BOOLEAN,
    IN p_Training_Philosophy_Agmt BOOLEAN,
    IN p_Affiliation_Policy_Agmt BOOLEAN,
    IN p_Security_Issue_Agmt BOOLEAN,
    IN p_Expulsion_Policy_Agmt BOOLEAN,
    IN p_Addressing_Individual_Child_Agmt BOOLEAN,
    IN p_Finalword_Agmt BOOLEAN
)
BEGIN
    UPDATE child_info
    SET
        parent_id = p_parent_id,
        additional_parent_id = p_additional_parent_id,
        classId = p_classId,
        care_provider_id = p_care_provider_id,
        dentist_id = p_dentist_id,
        child_first_name = p_child_first_name,
        child_last_name = p_child_last_name,
        nick_name = p_nick_name,
        dob = p_dob,
        primary_language = p_primary_language,
        school_age_child_school = p_school_age_child_school,
        custody_papers_apply = p_custody_papers_apply,
        gender = p_gender,
        special_diabilities = p_special_diabilities,
        allergies_reaction = p_allergies_reaction,
        additional_info = p_additional_info,
        medication = p_medication,
        health_insurance = p_health_insurance,
        policy_number = p_policy_number,
        emergency_medical_care = p_emergency_medical_care,
        first_aid_procedures = p_first_aid_procedures,
        physical_exam_last_date = p_physical_exam_last_date,
        dental_exam_last_date = p_dental_exam_last_date,
        allergies = p_allergies,
        asthma = p_asthma,
        bleeding_problems = p_bleeding_problems,
        diabetes = p_diabetes,
        epilepsy = p_epilepsy,
        frequent_ear_infections = p_frequent_ear_infections,
        frequent_illnesses = p_frequent_illnesses,
        hearing_problems = p_hearing_problems,
        high_fevers = p_high_fevers,
        hospitalization = p_hospitalization,
        rheumatic_fever = p_rheumatic_fever,
        seizures_convulsions = p_seizures_convulsions,
        serious_injuries_accidents = p_serious_injuries_accidents,
        surgeries = p_surgeries,
        vision_problems = p_vision_problems,
        medical_other = p_medical_other,
        illness_in_pregnancy = p_illness_in_pregnancy,
        condition_of_newborn = p_condition_of_newborn,
        duration_of_pregnancy = p_duration_of_pregnancy,
        birth_weight_lbs = p_birth_weight_lbs,
        birth_weight_oz = p_birth_weight_oz,
        complications = p_complications,
        bottle_fed = p_bottle_fed,
        breast_fed = p_breast_fed,
        fam_hist_allergies = p_fam_hist_allergies,
        fam_hist_heart_problems = p_fam_hist_heart_problems,
        fam_hist_tuberculosis = p_fam_hist_tuberculosis,
        fam_hist_asthma = p_fam_hist_asthma,
        fam_hist_high_blood_pressure = p_fam_hist_high_blood_pressure,
        fam_hist_vision_problems = p_fam_hist_vision_problems,
        fam_hist_diabetes = p_fam_hist_diabetes,
        fam_hist_hyperactivity = p_fam_hist_hyperactivity,
        fam_hist_epilepsy = p_fam_hist_epilepsy,
        fam_hist_no_illness = p_fam_hist_no_illness,
        other_siblings_name = p_other_siblings_name,
        other_siblings_age = p_other_siblings_age,
        age_group_friends = p_age_group_friends,
        neighborhood_friends = p_neighborhood_friends,
        relationship_with_mom = p_relationship_with_mom,
        relationship_with_dad = p_relationship_with_dad,
        relationship_with_sib = p_relationship_with_sib,
        relationship_extended_family = p_relationship_extended_family,
        fears_conflicts = p_fears_conflicts,
        c_response_frustration = p_c_response_frustration,
        favorite_activities = p_favorite_activities,
        last_five_years_moved = p_last_five_years_moved,
        things_used_home = p_things_used_home,
        hours_of_television_daily = p_hours_of_television_daily,
        language_at_home = p_language_at_home,
        changes_home_situation = p_changes_home_situation,
        educational_expectations_of_child = p_educational_expectations_of_child,
        important_fam_members = p_important_fam_members,
        fam_celebrations = p_fam_celebrations,
        childcare_before = p_childcare_before,
        reason_for_childcare_before = p_reason_for_childcare_before,
        what_child_interests = p_what_child_interests,
        drop_off_time = p_drop_off_time,
        pick_up_time = p_pick_up_time,
        restricted_diet = p_restricted_diet,
        restricted_diet_reason = p_restricted_diet_reason,
        eat_own = p_eat_own,
        eat_own_reason = p_eat_own_reason,
        favorite_foods = p_favorite_foods,
        rest_middle_day = p_rest_middle_day,
        reason_rest_middle_day = p_reason_rest_middle_day,
        rest_routine = p_rest_routine,
        toilet_trained = p_toilet_trained,
        reason_for_toilet_trained = p_reason_for_toilet_trained,
        existing_illness_allergy = p_existing_illness_allergy,
        explain_illness_allergy = p_explain_illness_allergy,
        functioning_at_age = p_functioning_at_age,
        explain_functioning_at_age = p_explain_functioning_at_age,
        able_to_walk = p_able_to_walk,
        explain_able_to_walk = p_explain_able_to_walk,
        communicate_their_needs = p_communicate_their_needs,
        explain_communicate_their_needs = p_explain_communicate_their_needs,
        any_medication = p_any_medication,
        explain_for_any_medication = p_explain_for_any_medication,
        special_equipment = p_special_equipment,
        explain_special_equipment = p_explain_special_equipment,
        significant_periods = p_significant_periods,
        explain_significant_periods = p_explain_significant_periods,
        accommodations = p_accommodations,
        explain_for_accommodations = p_explain_for_accommodations,
        additional_information = p_additional_information,
        child_info_is_correct = p_child_info_is_correct,
        above_nfo_is_correct = p_above_nfo_is_correct,
        immunization_instructions = p_immunization_instructions,
        profile_info = p_profile_info,
        child_pick_up_password = p_child_pick_up_password,
        pick_up_password_form = p_pick_up_password_form,
        photo_video_permission_form = p_photo_video_permission_form,
        photo_permission__electronic = p_photo_permission__electronic,
        security_release_policy_form = p_security_release_policy_form,
        med_technicians_med_transportation_waiver = p_med_technicians_med_transportation_waiver,
        medical_transportation_waiver = p_medical_transportation_waiver,
        health_policies = p_health_policies,
        parent_sign_outside_waiver = p_parent_sign_outside_waiver,
        approve_social_media_post = p_approve_social_media_post,
        printed_social_media_post = p_printed_social_media_post,
        social_media_post = p_social_media_post,
        bank_routing = p_bank_routing,
        bank_account = p_bank_account,
        driver_license = p_driver_license,
        state = p_state,
        myself = p_myself,
        enrollment_name = p_enrollment_name,
        point_one_field = p_point_one_field,
        point_two_init = p_point_two_init,
        point_three_ini = p_point_three_ini,
        point_four_init = p_point_four_init,
        point_five_init = p_point_five_init,
        point_six_init = p_point_six_init,
        point_seven_init = p_point_seven_init,
        point_eight_init = p_point_eight_init,
        point_nine_init = p_point_nine_init,
        point_ten_init = p_point_ten_init,
        point_eleven_init = p_point_eleven_init,
        point_twelve_init = p_point_twelve_init,
        point_thirteen_init = p_point_thirteen_init,
        point_fourteen_init = p_point_fourteen_init,
        point_fifteen_initi = p_point_fifteen_initi,
        point_sixteen_init = p_point_sixteen_init,
        point_seventeen_init = p_point_seventeen_init,
        point_eighteen_init = p_point_eighteen_init,
        start_date = p_start_date,
        schedule_date = p_schedule_date,
        full_day = p_full_day,
        half_day = p_half_day,
        Welcome_Goddard_Agmt = p_Welcome_Goddard_Agmt,
        Mission_Statement_Agmt = p_Mission_Statement_Agmt,
        General_Information_Agmt = p_General_Information_Agmt,
        Statement_Confidentiality_Agmt = p_Statement_Confidentiality_Agmt,
        Parent_Access_Agmt = p_Parent_Access_Agmt,
        Release_Children_Agmt = p_Release_Children_Agmt,
        Registration_Fees_Agmt = p_Registration_Fees_Agmt,
        Outside_Engagements_Agmt = p_Outside_Engagements_Agmt,
        Health_Policies_Agmt = p_Health_Policies_Agmt,
        Medication_Procedures_Agmt = p_Medication_Procedures_Agmt,
        Bring_school_Agmt = p_Bring_school_Agmt,
        Rest_Time_Agmt = p_Rest_Time_Agmt,
        Training_Philosophy_Agmt = p_Training_Philosophy_Agmt,
        Affiliation_Policy_Agmt = p_Affiliation_Policy_Agmt,
        Security_Issue_Agmt = p_Security_Issue_Agmt,
        Expulsion_Policy_Agmt = p_Expulsion_Policy_Agmt,
        Addressing_Individual_Child_Agmt = p_Addressing_Individual_Child_Agmt,
        Finalword_Agmt = p_Finalword_Agmt
    WHERE child_id = p_child_id;
END //

DELIMITER ;


