CREATE TABLE child_info (
    child_id INT PRIMARY KEY,
    parent_id INT,
    additional_parent_id INT,
    class_id INT,
    care_provider_id INT,
    dentist_id INT,
    child_first_name VARCHAR(255),
    child_last_name VARCHAR(255),
    nick_name VARCHAR(255),
    dob DATE,
    primary_language VARCHAR(100),
    school_age_child_school VARCHAR(255),
    custody_papers_apply VARCHAR(3), -- Example: 'yes' or 'no'
    gender VARCHAR(10),
    special_diabilities VARCHAR(3), -- Example: 'yes' or 'no'
    allergies_reaction VARCHAR(3), -- Example: 'yes' or 'no'
    additional_info TEXT,
    medication VARCHAR(255),
    health_insurance VARCHAR(255),
    policy_number VARCHAR(50),
    emergency_medical_care VARCHAR(255),
    first_aid_procedures VARCHAR(255),
    physical_exam_last_date DATE,
    dental_exam_last_date DATE,
    allergies VARCHAR(3), -- Example: 'yes' or 'no'
    asthma VARCHAR(3), -- Example: 'yes' or 'no'
    bleeding_problems VARCHAR(3), -- Example: 'yes' or 'no'
    diabetes VARCHAR(3), -- Example: 'yes' or 'no'
    epilepsy VARCHAR(3), -- Example: 'yes' or 'no'
    frequent_ear_infections VARCHAR(3), -- Example: 'yes' or 'no'
    frequent_illnesses VARCHAR(3), -- Example: 'yes' or 'no'
    hearing_problems VARCHAR(3), -- Example: 'yes' or 'no'
    high_fevers VARCHAR(3), -- Example: 'yes' or 'no'
    hospitalization VARCHAR(3), -- Example: 'yes' or 'no'
    rheumatic_fever VARCHAR(3), -- Example: 'yes' or 'no'
    seizures_convulsions VARCHAR(3), -- Example: 'yes' or 'no'
    serious_injuries_accidents VARCHAR(3), -- Example: 'yes' or 'no'
    surgeries VARCHAR(3), -- Example: 'yes' or 'no'
    vision_problems VARCHAR(3), -- Example: 'yes' or 'no'
    medical_other TEXT,
    illness_in_pregnancy VARCHAR(3), -- Example: 'yes' or 'no'
    condition_of_newborn VARCHAR(3), -- Example: 'yes' or 'no'
    duration_of_pregnancy VARCHAR(50),
    birth_weight_lbs INT,
    birth_weight_oz INT,
    complications VARCHAR(3), -- Example: 'yes' or 'no'
    bottle_fed VARCHAR(3), -- Example: 'yes' or 'no'
    breast_fed VARCHAR(3), -- Example: 'yes' or 'no'
    fam_hist_allergies VARCHAR(3), -- Example: 'yes' or 'no'
    fam_hist_heart_problems VARCHAR(3), -- Example: 'yes' or 'no'
    fam_hist_tuberculosis VARCHAR(3), -- Example: 'yes' or 'no'
    fam_hist_asthma VARCHAR(3), -- Example: 'yes' or 'no'
    fam_hist_high_blood_pressure VARCHAR(3), -- Example: 'yes' or 'no'
    fam_hist_vision_problems VARCHAR(3), -- Example: 'yes' or 'no'
    fam_hist_diabetes VARCHAR(3), -- Example: 'yes' or 'no'
    fam_hist_hyperactivity VARCHAR(3), -- Example: 'yes' or 'no'
    fam_hist_epilepsy VARCHAR(3), -- Example: 'yes' or 'no'
    fam_hist_no_illness VARCHAR(3), -- Example: 'yes' or 'no'
    other_siblings_name VARCHAR(255),
    other_siblings_age VARCHAR(255),
    age_group_friends VARCHAR(50),
    neighborhood_friends VARCHAR(255),
    relationship_with_mom VARCHAR(255),
    relationship_with_dad VARCHAR(255),
    relationship_with_sib VARCHAR(255),
    relationship_extended_family VARCHAR(255),
    fears_conflicts VARCHAR(255),
    c_response_frustration VARCHAR(255),
    favorite_activities TEXT,
    last_five_years_moved VARCHAR(3), -- Example: 'yes' or 'no'
    things_used_home VARCHAR(255),
    hours_of_television_daily VARCHAR(255),
    language_at_home VARCHAR(100),
    changes_home_situation VARCHAR(3), -- Example: 'yes' or 'no'
    educational_expectations_of_child TEXT,
    important_fam_members VARCHAR(255),
    fam_celebrations VARCHAR(255),
    childcare_before VARCHAR(255),
    reason_for_childcare_before TEXT,
    what_child_interests TEXT,
    drop_off_time TIME,
    pick_up_time TIME,
    restricted_diet VARCHAR(3), -- Example: 'yes' or 'no'
    restricted_diet_reason TEXT,
    eat_own VARCHAR(3), -- Example: 'yes' or 'no'
    eat_own_reason TEXT,
    favorite_foods TEXT,
    rest_middle_day VARCHAR(3), -- Example: 'yes' or 'no'
    reason_rest_middle_day TEXT,
    rest_routine VARCHAR(255),
    toilet_trained VARCHAR(3), -- Example: 'yes' or 'no'
    reason_for_toilet_trained TEXT,
    existing_illness_allergy VARCHAR(3), -- Example: 'yes' or 'no'
    explain_illness_allergy TEXT,
    functioning_at_age VARCHAR(255),
    explain_functioning_at_age TEXT,
    able_to_walk VARCHAR(3), -- Example: 'yes' or 'no'
    explain_able_to_walk TEXT,
    communicate_their_needs VARCHAR(3), -- Example: 'yes' or 'no'
    explain_communicate_their_needs TEXT,
    any_medication VARCHAR(3), -- Example: 'yes' or 'no'
    explain_for_any_medication TEXT,
    special_equipment VARCHAR(3), -- Example: 'yes' or 'no'
    explain_special_equipment TEXT,
    significant_periods VARCHAR(255),
    explain_significant_periods TEXT,
    accommodations VARCHAR(3), -- Example: 'yes' or 'no'
    explain_for_accommodations TEXT,
    additional_information TEXT,
    child_info_is_correct VARCHAR(3), -- Example: 'yes' or 'no'
    above_nfo_is_correct VARCHAR(3), -- Example: 'yes' or 'no'
    immunization_instructions TEXT,
    profile_info TEXT,
    child_pick_up_password VARCHAR(255),
    pick_up_password_form VARCHAR(255),
    photo_video_permission_form VARCHAR(3), -- Example: 'yes' or 'no'
    photo_permission__electronic VARCHAR(3), -- Example: 'yes' or 'no'
    security_release_policy_form VARCHAR(3), -- Example: 'yes' or 'no'
    med_technicians_med_transportation_waiver VARCHAR(3), -- Example: 'yes' or 'no'
    medical_transportation_waiver VARCHAR(3), -- Example: 'yes' or 'no'
    health_policies VARCHAR(3), -- Example: 'yes' or 'no'
    parent_sign_outside_waiver VARCHAR(3), -- Example: 'yes' or 'no'
    approve_social_media_post VARCHAR(3), -- Example: 'yes' or 'no'
    printed_social_media_post VARCHAR(3), -- Example: 'yes' or 'no'
    social_media_post TEXT,
    bank_routing VARCHAR(255),
    bank_account VARCHAR(255),
    driver_license VARCHAR(255),
    state VARCHAR(255),
    myself VARCHAR(255),
    enrollment_name VARCHAR(255),
    point_one_field VARCHAR(255),
    point_two_init VARCHAR(255),
    point_three_ini VARCHAR(255),
    point_four_init VARCHAR(255),
    point_five_init VARCHAR(255),
    point_six_init VARCHAR(255),
    point_seven_init VARCHAR(255),
    point_eight_init VARCHAR(255),
    point_nine_init VARCHAR(255),
    point_ten_init VARCHAR(255),
    point_eleven_init VARCHAR(255),
    point_twelve_init VARCHAR(255),
    point_thirteen_init VARCHAR(255),
    point_fourteen_init VARCHAR(255),
    point_fifteen_initi VARCHAR(255),
    point_sixteen_init VARCHAR(255),
    point_seventeen_init VARCHAR(255),
    point_eighteen_init VARCHAR(255),
    start_date DATE,
    schedule_date DATE,
    full_day VARCHAR(3),
    half_day VARCHAR(3), 
    Welcome_Goddard_Agmt VARCHAR(3), 
    Mission_Statement_Agmt VARCHAR(3), 
    General_Information_Agmt VARCHAR(3), 
    Statement_Confidentiality_Agmt VARCHAR(3), 
    Parent_Access_Agmt VARCHAR(3), 
    Release_Children_Agmt VARCHAR(3),
    Registration_Fees_Agmt VARCHAR(3), 
    Outside_Engagements_Agmt VARCHAR(3), 
    Health_Policies_Agmt VARCHAR(3), 
	Medication_Procedures_Agmt VARCHAR(3), 
	Bring_school_Agmt VARCHAR(3),
	Rest_Time_Agmt VARCHAR(3), 
	Training_Philosophy_Agmt VARCHAR(3),
	Affiliation_Policy_Agmt VARCHAR(3), 
	Security_Issue_Agmt VARCHAR(3), 
	Expulsion_Policy_Agmt VARCHAR(3), 
	Addressing_Individual_Child_Agmt VARCHAR(3),
	Finalword_Agmt VARCHAR(3) 
	);


    # create delete call store procedure:
 DELIMITER //

CREATE PROCEDURE DeleteChildInfo (
    IN child_id_param INT
)
BEGIN
    DELETE FROM child_info
    WHERE child_id = child_id_param;
END //

DELIMITER ;


DELIMITER //

CREATE PROCEDURE InsertChildInfo(
    IN p_parent_id INT,
    IN p_additional_parent_id INT,
    IN p_class_id INT,
    IN p_care_provider_id INT,
    IN p_dentist_id INT,
    IN p_child_first_name VARCHAR(255),
    IN p_child_last_name VARCHAR(255),
    IN p_nick_name VARCHAR(255),
    IN p_dob DATE,
    IN p_primary_language VARCHAR(100),
    IN p_school_age_child_school VARCHAR(255),
    IN p_custody_papers_apply VARCHAR(3),
    IN p_gender VARCHAR(10),
    IN p_special_diabilities VARCHAR(3),
    IN p_allergies_reaction VARCHAR(3),
    IN p_additional_info TEXT,
    IN p_medication VARCHAR(255),
    IN p_health_insurance VARCHAR(255),
    IN p_policy_number VARCHAR(50),
    IN p_emergency_medical_care VARCHAR(255),
    IN p_first_aid_procedures VARCHAR(255),
    IN p_physical_exam_last_date DATE,
    IN p_dental_exam_last_date DATE,
    IN p_allergies VARCHAR(3),
    IN p_asthma VARCHAR(3),
    IN p_bleeding_problems VARCHAR(3),
    IN p_diabetes VARCHAR(3),
    IN p_epilepsy VARCHAR(3),
    IN p_frequent_ear_infections VARCHAR(3),
    IN p_frequent_illnesses VARCHAR(3),
    IN p_hearing_problems VARCHAR(3),
    IN p_high_fevers VARCHAR(3),
    IN p_hospitalization VARCHAR(3),
    IN p_rheumatic_fever VARCHAR(3),
    IN p_seizures_convulsions VARCHAR(3),
    IN p_serious_injuries_accidents VARCHAR(3),
    IN p_surgeries VARCHAR(3),
    IN p_vision_problems VARCHAR(3),
    IN p_medical_other TEXT,
    IN p_illness_in_pregnancy VARCHAR(3),
    IN p_condition_of_newborn VARCHAR(3),
    IN p_duration_of_pregnancy VARCHAR(50),
    IN p_birth_weight_lbs INT,
    IN p_birth_weight_oz INT,
    IN p_complications VARCHAR(3),
    IN p_bottle_fed VARCHAR(3),
    IN p_breast_fed VARCHAR(3),
    IN p_fam_hist_allergies VARCHAR(3),
    IN p_fam_hist_heart_problems VARCHAR(3),
    IN p_fam_hist_tuberculosis VARCHAR(3),
    IN p_fam_hist_asthma VARCHAR(3),
    IN p_fam_hist_high_blood_pressure VARCHAR(3),
    IN p_fam_hist_vision_problems VARCHAR(3),
    IN p_fam_hist_diabetes VARCHAR(3),
    IN p_fam_hist_hyperactivity VARCHAR(3),
    IN p_fam_hist_epilepsy VARCHAR(3),
    IN p_fam_hist_no_illness VARCHAR(3),
    IN p_other_siblings_name VARCHAR(255),
    IN p_other_siblings_age VARCHAR(255),
    IN p_age_group_friends VARCHAR(50),
    IN p_neighborhood_friends VARCHAR(255),
    IN p_relationship_with_mom VARCHAR(255),
    IN p_relationship_with_dad VARCHAR(255),
    IN p_relationship_with_sib VARCHAR(255),
    IN p_relationship_extended_family VARCHAR(255),
    IN p_fears_conflicts VARCHAR(255),
    IN p_c_response_frustration VARCHAR(255),
    IN p_favorite_activities TEXT,
    IN p_last_five_years_moved VARCHAR(3),
    IN p_things_used_home VARCHAR(255),
    IN p_hours_of_television_daily VARCHAR(255),
    IN p_language_at_home VARCHAR(100),
    IN p_changes_home_situation VARCHAR(3),
    IN p_educational_expectations_of_child TEXT,
    IN p_important_fam_members VARCHAR(255),
    IN p_fam_celebrations VARCHAR(255),
    IN p_childcare_before VARCHAR(255),
    IN p_reason_for_childcare_before TEXT,
    IN p_what_child_interests TEXT,
    IN p_drop_off_time TIME,
    IN p_pick_up_time TIME,
    IN p_restricted_diet VARCHAR(3),
    IN p_restricted_diet_reason TEXT,
    IN p_eat_own VARCHAR(3),
    IN p_eat_own_reason TEXT,
    IN p_favorite_foods TEXT,
    IN p_rest_middle_day VARCHAR(3),
    IN p_reason_rest_middle_day TEXT,
    IN p_rest_routine VARCHAR(255),
    IN p_toilet_trained VARCHAR(3),
    IN p_reason_for_toilet_trained TEXT,
    IN p_existing_illness_allergy VARCHAR(3),
    IN p_explain_illness_allergy TEXT,
    IN p_functioning_at_age VARCHAR(255),
    IN p_explain_functioning_at_age TEXT,
    IN p_able_to_walk VARCHAR(3),
    IN p_explain_able_to_walk TEXT,
    IN p_communicate_their_needs VARCHAR(3),
    IN p_explain_communicate_their_needs TEXT,
    IN p_any_medication VARCHAR(3),
    IN p_explain_for_any_medication TEXT,
    IN p_special_equipment VARCHAR(3),
    IN p_explain_special_equipment TEXT,
    IN p_significant_periods VARCHAR(255),
    IN p_explain_significant_periods TEXT,
    IN p_accommodations VARCHAR(3),
    IN p_explain_for_accommodations TEXT,
    IN p_additional_information TEXT,
    IN p_child_info_is_correct VARCHAR(3),
    IN p_above_nfo_is_correct VARCHAR(3),
    IN p_immunization_instructions TEXT,
    IN p_profile_info TEXT,
    IN p_child_pick_up_password VARCHAR(255),
    IN p_pick_up_password_form VARCHAR(255),
    IN p_photo_video_permission_form VARCHAR(3),
    IN p_photo_permission__electronic VARCHAR(3),
    IN p_security_release_policy_form VARCHAR(3),
    IN p_med_technicians_med_transportation_waiver VARCHAR(3),
    IN p_medical_transportation_waiver VARCHAR(3),
    IN p_health_policies VARCHAR(3),
    IN p_parent_sign_outside_waiver VARCHAR(3),
    IN p_approve_social_media_post VARCHAR(3),
    IN p_printed_social_media_post VARCHAR(3),
    IN p_social_media_post TEXT,
    IN p_bank_routing VARCHAR(255),
    IN p_bank_account VARCHAR(255),
    IN p_driver_license VARCHAR(255),
    IN p_state VARCHAR(255),
    IN p_myself VARCHAR(255),
    IN p_enrollment_name VARCHAR(255),
    IN p_point_one_field VARCHAR(255),
    IN p_point_two_init VARCHAR(255),
    IN p_point_three_ini VARCHAR(255),
    IN p_point_four_init VARCHAR(255),
    IN p_point_five_init VARCHAR(255),
    IN p_point_six_init VARCHAR(255),
    IN p_point_seven_init VARCHAR(255),
    IN p_point_eight_init VARCHAR(255),
    IN p_point_nine_init VARCHAR(255),
    IN p_point_ten_init VARCHAR(255),
    IN p_point_eleven_init VARCHAR(255),
    IN p_point_twelve_init VARCHAR(255),
    IN p_point_thirteen_init VARCHAR(255),
    IN p_point_fourteen_init VARCHAR(255),
    IN p_point_fifteen_initi VARCHAR(255),
    IN p_point_sixteen_init VARCHAR(255),
    IN p_point_seventeen_init VARCHAR(255),
    IN p_point_eighteen_init VARCHAR(255),
    IN p_start_date DATE,
    IN p_schedule_date DATE,
    IN p_full_day VARCHAR(3),
    IN p_half_day VARCHAR(3),
    IN p_Welcome_Goddard_Agmt VARCHAR(3),
    IN p_Mission_Statement_Agmt VARCHAR(3),
    IN p_General_Information_Agmt VARCHAR(3),
    IN p_Statement_Confidentiality_Agmt VARCHAR(3),
    IN p_Parent_Access_Agmt VARCHAR(3),
    IN p_Release_Children_Agmt VARCHAR(3),
    IN p_Registration_Fees_Agmt VARCHAR(3),
    IN p_Outside_Engagements_Agmt VARCHAR(3),
    IN p_Health_Policies_Agmt VARCHAR(3),
    IN p_Medication_Procedures_Agmt VARCHAR(3),
    IN p_Bring_school_Agmt VARCHAR(3),
    IN p_Rest_Time_Agmt VARCHAR(3),
    IN p_Training_Philosophy_Agmt VARCHAR(3),
    IN p_Affiliation_Policy_Agmt VARCHAR(3),
    IN p_Security_Issue_Agmt VARCHAR(3),
    IN p_Expulsion_Policy_Agmt VARCHAR(3),
    IN p_Addressing_Individual_Child_Agmt VARCHAR(3),
    IN p_Finalword_Agmt VARCHAR(3)
)
BEGIN
    INSERT INTO child_info (
        parent_id,
        additional_parent_id,
        class_id,
        care_provider_id,
        dentist_id,
        child_first_name,
        child_last_name,
        nick_name,
        dob,
        primary_language,
        school_age_child_school,
        custody_papers_apply,
        gender,
        special_diabilities,
        allergies_reaction,
        additional_info,
        medication,
        health_insurance,
        policy_number,
        emergency_medical_care,
        first_aid_procedures,
        physical_exam_last_date,
        dental_exam_last_date,
        allergies,
        asthma,
        bleeding_problems,
        diabetes,
        epilepsy,
        frequent_ear_infections,
        frequent_illnesses,
        hearing_problems,
        high_fevers,
        hospitalization,
        rheumatic_fever,
        seizures_convulsions,
        serious_injuries_accidents,
        surgeries,
        vision_problems,
        medical_other,
        illness_in_pregnancy,
        condition_of_newborn,
        duration_of_pregnancy,
        birth_weight_lbs,
        birth_weight_oz,
        complications,
        bottle_fed,
        breast_fed,
        fam_hist_allergies,
        fam_hist_heart_problems,
        fam_hist_tuberculosis,
        fam_hist_asthma,
        fam_hist_high_blood_pressure,
        fam_hist_vision_problems,
        fam_hist_diabetes,
        fam_hist_hyperactivity,
        fam_hist_epilepsy,
        fam_hist_no_illness,
        other_siblings_name,
        other_siblings_age,
        age_group_friends,
        neighborhood_friends,
        relationship_with_mom,
        relationship_with_dad,
        relationship_with_sib,
        relationship_extended_family,
        fears_conflicts,
        c_response_frustration,
        favorite_activities,
        last_five_years_moved,
        things_used_home,
        hours_of_television_daily,
        language_at_home,
        changes_home_situation,
        educational_expectations_of_child,
        important_fam_members,
        fam_celebrations,
        childcare_before,
        reason_for_childcare_before,
        what_child_interests,
        drop_off_time,
        pick_up_time,
        restricted_diet,
        restricted_diet_reason,
        eat_own,
        eat_own_reason,
        favorite_foods,
        rest_middle_day,
        reason_rest_middle_day,
        rest_routine,
        toilet_trained,
        reason_for_toilet_trained,
        existing_illness_allergy,
        explain_illness_allergy,
        functioning_at_age,
        explain_functioning_at_age,
        able_to_walk,
        explain_able_to_walk,
        communicate_their_needs,
        explain_communicate_their_needs,
        any_medication,
        explain_for_any_medication,
        special_equipment,
        explain_special_equipment,
        significant_periods,
        explain_significant_periods,
        accommodations,
        explain_for_accommodations,
        additional_information,
        child_info_is_correct,
        above_nfo_is_correct,
        immunization_instructions,
        profile_info,
        child_pick_up_password,
        pick_up_password_form,
        photo_video_permission_form,
        photo_permission__electronic,
        security_release_policy_form,
        med_technicians_med_transportation_waiver,
        medical_transportation_waiver,
        health_policies,
        parent_sign_outside_waiver,
        approve_social_media_post,
        printed_social_media_post,
        social_media_post,
        bank_routing,
        bank_account,
        driver_license,
        state,
        myself,
        enrollment_name,
        point_one_field,
        point_two_init,
        point_three_ini,
        point_four_init,
        point_five_init,
        point_six_init,
        point_seven_init,
        point_eight_init,
        point_nine_init,
        point_ten_init,
        point_eleven_init,
        point_twelve_init,
        point_thirteen_init,
        point_fourteen_init,
        point_fifteen_initi,
        point_sixteen_init,
        point_seventeen_init,
        point_eighteen_init,
        start_date,
        schedule_date,
        full_day,
        half_day,
        Welcome_Goddard_Agmt,
        Mission_Statement_Agmt,
        General_Information_Agmt,
        Statement_Confidentiality_Agmt,
        Parent_Access_Agmt,
        Release_Children_Agmt,
        Registration_Fees_Agmt,
        Outside_Engagements_Agmt,
        Health_Policies_Agmt,
        Medication_Procedures_Agmt,
        Bring_school_Agmt,
        Rest_Time_Agmt,
        Training_Philosophy_Agmt,
        Affiliation_Policy_Agmt,
        Security_Issue_Agmt,
        Expulsion_Policy_Agmt,
        Addressing_Individual_Child_Agmt,
        Finalword_Agmt
    )
    VALUES (
        p_parent_id,
        p_additional_parent_id,
        p_class_id,
        p_care_provider_id,
        p_dentist_id,
        p_child_first_name,
        p_child_last_name,
        p_nick_name,
        p_dob,
        p_primary_language,
        p_school_age_child_school,
        p_custody_papers_apply,
        p_gender,
        p_special_diabilities,
        p_allergies_reaction,
        p_additional_info,
        p_medication,
        p_health_insurance,
        p_policy_number,
        p_emergency_medical_care,
        p_first_aid_procedures,
        p_physical_exam_last_date,
        p_dental_exam_last_date,
        p_allergies,
        p_asthma,
        p_bleeding_problems,
        p_diabetes,
        p_epilepsy,
        p_frequent_ear_infections,
        p_frequent_illnesses,
        p_hearing_problems,
        p_high_fevers,
        p_hospitalization,
        p_rheumatic_fever,
        p_seizures_convulsions,
        p_serious_injuries_accidents,
        p_surgeries,
        p_vision_problems,
        p_medical_other,
        p_illness_in_pregnancy,
        p_condition_of_newborn,
        p_duration_of_pregnancy,
        p_birth_weight_lbs,
        p_birth_weight_oz,
        p_complications,
        p_bottle_fed,
        p_breast_fed,
        p_fam_hist_allergies,
        p_fam_hist_heart_problems,
        p_fam_hist_tuberculosis,
        p_fam_hist_asthma,
        p_fam_hist_high_blood_pressure,
        p_fam_hist_vision_problems,
        p_fam_hist_diabetes,
        p_fam_hist_hyperactivity,
        p_fam_hist_epilepsy,
        p_fam_hist_no_illness,
        p_other_siblings_name,
        p_other_siblings_age,
        p_age_group_friends,
        p_neighborhood_friends,
        p_relationship_with_mom,
        p_relationship_with_dad,
        p_relationship_with_sib,
        p_relationship_extended_family,
        p_fears_conflicts,
        p_c_response_frustration,
        p_favorite_activities,
        p_last_five_years_moved,
        p_things_used_home,
        p_hours_of_television_daily,
        p_language_at_home,
        p_changes_home_situation,
        p_educational_expectations_of_child,
        p_important_fam_members,
        p_fam_celebrations,
        p_childcare_before,
        p_reason_for_childcare_before,
        p_what_child_interests,
        p_drop_off_time,
        p_pick_up_time,
        p_restricted_diet,
        p_restricted_diet_reason,
        p_eat_own,
        p_eat_own_reason,
        p_favorite_foods,
        p_rest_middle_day,
        p_reason_rest_middle_day,
        p_rest_routine,
        p_toilet_trained,
        p_reason_for_toilet_trained,
        p_existing_illness_allergy,
        p_explain_illness_allergy,
        p_functioning_at_age,
        p_explain_functioning_at_age,
        p_able_to_walk,
        p_explain_able_to_walk,
        p_communicate_their_needs,
        p_explain_communicate_their_needs,
        p_any_medication,
        p_explain_for_any_medication,
        p_special_equipment,
        p_explain_special_equipment,
        p_significant_periods,
        p_explain_significant_periods,
        p_accommodations,
        p_explain_for_accommodations,
        p_additional_information,
        p_child_info_is_correct,
        p_above_nfo_is_correct,
        p_immunization_instructions,
        p_profile_info,
        p_child_pick_up_password,
        p_pick_up_password_form,
        p_photo_video_permission_form,
        p_photo_permission__electronic,
        p_security_release_policy_form,
        p_med_technicians_med_transportation_waiver,
        p_medical_transportation_waiver,
        p_health_policies,
        p_parent_sign_outside_waiver,
        p_approve_social_media_post,
        p_printed_social_media_post,
        p_social_media_post,
        p_bank_routing,
        p_bank_account,
        p_driver_license,
        p_state,
        p_myself,
        p_enrollment_name,
        p_point_one_field,
        p_point_two_init,
        p_point_three_ini,
        p_point_four_init,
        p_point_five_init,
        p_point_six_init,
        p_point_seven_init,
        p_point_eight_init,
        p_point_nine_init,
        p_point_ten_init,
        p_point_eleven_init,
        p_point_twelve_init,
        p_point_thirteen_init,
        p_point_fourteen_init,
        p_point_fifteen_initi,
        p_point_sixteen_init,
        p_point_seventeen_init,
        p_point_eighteen_init,
        p_start_date,
        p_schedule_date,
        p_full_day,
        p_half_day,
        p_Welcome_Goddard_Agmt,
        p_Mission_Statement_Agmt,
        p_General_Information_Agmt,
        p_Statement_Confidentiality_Agmt,
        p_Parent_Access_Agmt,
        p_Release_Children_Agmt,
        p_Registration_Fees_Agmt,
        p_Outside_Engagements_Agmt,
        p_Health_Policies_Agmt,
        p_Medication_Procedures_Agmt,
        p_Bring_school_Agmt,
        p_Rest_Time_Agmt,
        p_Training_Philosophy_Agmt,
        p_Affiliation_Policy_Agmt,
        p_Security_Issue_Agmt,
        p_Expulsion_Policy_Agmt,
        p_Address_Individual_Child_Agmt,
        p_Finalword_Agmt
    );
END //

DELIMITER ;
 
#getbyid
 DELIMITER //

CREATE PROCEDURE get_child_info_by_id(
    IN p_child_id INT
)
BEGIN
    SELECT *
    FROM child_info
    WHERE child_id = p_child_id;
END //

DELIMITER ;

#getall

DELIMITER //

CREATE PROCEDURE get_all_child_info()
BEGIN
    SELECT * FROM child_info;
END //

DELIMITER ;

