DELIMITER $$

CREATE PROCEDURE `CreateChildInfo`(
    IN p_parent_id VARCHAR(255),
    IN p_additional_parent_id VARCHAR(255),
    IN p_class_id INT,
    IN p_care_provider_id INT,
    IN p_dentist_id INT,
    IN p_child_first_name VARCHAR(255),
    IN p_child_last_name VARCHAR(255),
    IN p_nick_name VARCHAR(255),
    IN p_dob DATE,
    IN p_primary_language VARCHAR(50),
    IN p_school_age_child_school VARCHAR(255),
    IN p_do_relevant_custody_papers_apply BOOLEAN,
    IN p_gender VARCHAR(10),
    IN p_special_disabilities TEXT,
    IN p_allergies_medication_reaction TEXT,
    IN p_additional_info TEXT,
    IN p_medication TEXT,
    IN p_health_insurance VARCHAR(255),
    IN p_policy_number VARCHAR(50),
    IN p_obtaining_emergency_medical_care BOOLEAN,
    IN p_administration_first_aid_procedures BOOLEAN,
    IN p_physical_exam_last_date DATE,
    IN p_dental_exam_last_date DATE,
    IN p_allergies BOOLEAN,
    IN p_asthma BOOLEAN,
    IN p_bleeding_problems BOOLEAN,
    IN p_diabetes BOOLEAN,
    IN p_epilepsy BOOLEAN,
    IN p_frequent_ear_infections BOOLEAN,
    IN p_frequent_illnesses BOOLEAN,
    IN p_hearing_problems BOOLEAN,
    IN p_high_fevers BOOLEAN,
    IN p_hospitalization BOOLEAN,
    IN p_rheumatic_fever BOOLEAN,
    IN p_seizures_convulsions BOOLEAN,
    IN p_serious_injuries_accidents BOOLEAN,
    IN p_surgeries BOOLEAN,
    IN p_vision_problems BOOLEAN,
    IN p_medical_other TEXT,
    IN p_illness_during_pregnancy BOOLEAN,
    IN p_condition_of_newborn VARCHAR(255),
    IN p_duration_of_pregnancy VARCHAR(50),
    IN p_birth_weight_lbs INT,
    IN p_birth_weight_oz INT,
    IN p_complications TEXT,
    IN p_bottle_fed BOOLEAN,
    IN p_breast_fed BOOLEAN,
    IN p_family_history_allergies BOOLEAN,
    IN p_family_history_heart_problems BOOLEAN,
    IN p_family_history_tuberculosis BOOLEAN,
    IN p_family_history_asthma BOOLEAN,
    IN p_family_history_high_blood_pressure BOOLEAN,
    IN p_family_history_vision_problems BOOLEAN,
    IN p_family_history_diabetes BOOLEAN,
    IN p_family_history_hyperactivity BOOLEAN,
    IN p_family_history_epilepsy BOOLEAN,
    IN p_family_history_no_illness BOOLEAN,
    IN p_other_siblings_name VARCHAR(255),
    IN p_other_siblings_age INT,
    IN p_age_group_friends VARCHAR(255),
    IN p_neighborhood_friends VARCHAR(255),
    IN p_relationship_with_mother VARCHAR(255),
    IN p_relationship_with_father VARCHAR(255),
    IN p_relationship_with_siblings VARCHAR(255),
    IN p_relationship_with_extended_family VARCHAR(255),
    IN p_fears_conflicts TEXT,
    IN p_child_response_frustration TEXT,
    IN p_favorite_activities TEXT,
    IN p_last_five_years_moved BOOLEAN,
    IN p_things_used_at_home TEXT,
    IN p_hours_of_television_daily INT,
    IN p_language_used_at_home VARCHAR(50),
    IN p_changes_at_home_situation TEXT,
    IN p_educational_expectations_of_child TEXT,
    IN p_other_important_family_members TEXT,
    IN p_about_family_celebrations TEXT,
    IN p_childcare_before BOOLEAN,
    IN p_reason_for_childcare_before TEXT,
    IN p_what_child_interests TEXT,
    IN p_drop_off_time TIME,
    IN p_pick_up_time TIME,
    IN p_restricted_diet BOOLEAN,
    IN p_restricted_diet_reason TEXT,
    IN p_eat_own BOOLEAN,
    IN p_eat_own_reason TEXT,
    IN p_favorite_foods TEXT,
    IN p_rest_in_the_middle_day BOOLEAN,
    IN p_reason_for_rest_in_the_middle_day TEXT,
    IN p_rest_routine TEXT,
    IN p_toilet_trained BOOLEAN,
    IN p_reason_for_toilet_trained TEXT,
    IN p_existing_illness_allergy BOOLEAN,
    IN p_explain_for_existing_illness_allergy TEXT,
    IN p_functioning_at_age BOOLEAN,
    IN p_explain_for_functioning_at_age TEXT,
    IN p_able_to_walk BOOLEAN,
    IN p_explain_for_able_to_walk TEXT,
    IN p_communicate_their_needs BOOLEAN,
    IN p_explain_for_communicate_their_needs TEXT,
    IN p_any_medication BOOLEAN,
    IN p_explain_for_any_medication TEXT,
    IN p_utilize_special_equipment BOOLEAN,
    IN p_explain_for_utilize_special_equipment TEXT,
    IN p_significant_periods BOOLEAN,
    IN p_explain_for_significant_periods TEXT,
    IN p_desire_any_accommodations BOOLEAN,
    IN p_explain_for_desire_any_accommodations TEXT,
    IN p_additional_information TEXT,
    IN p_agree_all_child_information_is_correct BOOLEAN,
    IN p_agree_all_above_information_is_correct BOOLEAN,
    IN p_do_you_agree_this_immunization_instructions BOOLEAN,
    IN p_do_you_agree_profile_information BOOLEAN,
    IN p_child_password_pick_up_password_form VARCHAR(255),
    IN p_do_you_agree_this_pick_up_password_form BOOLEAN,
    IN p_photo_usage_photo_video_permission_form BOOLEAN,
    IN p_photo_permission_agree_group_photos_electronic BOOLEAN,
    IN p_do_you_agree_this_photo_video_permission_form BOOLEAN,
    IN p_do_you_agree_this_security_release_policy_form BOOLEAN,
    IN p_contact_emergency_medical_technicians_medical_transportation_waiver BOOLEAN,
    IN p_do_you_agree_this_medical_transportation_waiver BOOLEAN,
    IN p_do_you_agree_this_health_policies BOOLEAN,
    IN p_outside_waiver_parent_sign_outside_engagements_waiver BOOLEAN,
    IN p_approve_social_media_post BOOLEAN,
    IN p_printed_name_social_media_post VARCHAR(255),
    IN p_do_you_agree_this_social_media_post BOOLEAN,
    IN p_bank_routing VARCHAR(50),
    IN p_bank_account VARCHAR(50),
    IN p_driver_license VARCHAR(50),
    IN p_state VARCHAR(50),
    IN p_myself BOOLEAN,
    IN p_enrollment_name VARCHAR(255),
    IN p_point_one_field_three TEXT,
    IN p_point_two_initial_here TEXT,
    IN p_point_three_initial_here TEXT,
    IN p_point_four_initial_here TEXT,
    IN p_point_five_initial_here TEXT,
    IN p_point_six_initial_here TEXT,
    IN p_point_seven_initial_here TEXT,
    IN p_point_eight_initial_here TEXT,
    IN p_point_nine_initial_here TEXT,
    IN p_point_ten_initial_here TEXT,
    IN p_point_eleven_initial_here TEXT,
    IN p_point_twelve_initial_here TEXT,
    IN p_point_thirteen_initial_here TEXT,
    IN p_point_fourteen_initial_here TEXT,
    IN p_point_fifteen_initial_here TEXT,
    IN p_point_sixteen_initial_here TEXT,
    IN p_point_seventeen_initial_here TEXT,
    IN p_point_eighteen_initial_here TEXT,
    IN p_preferred_start_date DATE,
    IN p_preferred_schedule VARCHAR(255),
    IN p_full_day BOOLEAN,
    IN p_half_day BOOLEAN,
    IN p_welcome_goddard_agreement BOOLEAN,
    IN p_mission_statement_agreement BOOLEAN,
    IN p_general_information_agreement BOOLEAN,
    IN p_statement_of_confidentiality BOOLEAN,
    IN p_parent_access_agreement BOOLEAN,
    IN p_release_of_children_agreement BOOLEAN,
    IN p_registration_fees_agreement BOOLEAN,
    IN p_outside_engagements_agreement BOOLEAN,
    IN p_health_policies_agreement BOOLEAN,
    IN p_medication_procedures_agreement BOOLEAN,
    IN p_bring_to_school_agreement BOOLEAN,
    IN p_rest_time_agreement BOOLEAN,
    IN p_training_philosophy_agreement BOOLEAN,
    IN p_affiliation_policy_agreement BOOLEAN,
    IN p_security_issue_agreement BOOLEAN,
    IN p_expulsion_policy_agreement BOOLEAN,
    IN p_addressing_individual_child_agreement BOOLEAN,
    IN p_finalword_agreement BOOLEAN
)
BEGIN
    INSERT INTO child_info (
        parent_id, additional_parent_id, class_id, care_provider_id, dentist_id, child_first_name, child_last_name, nick_name, dob, primary_language,
        school_age_child_school, do_relevant_custody_papers_apply, gender, special_disabilities, allergies_medication_reaction, additional_info, medication,
        health_insurance, policy_number, obtaining_emergency_medical_care, administration_first_aid_procedures, physical_exam_last_date, dental_exam_last_date,
        allergies, asthma, bleeding_problems, diabetes, epilepsy, frequent_ear_infections, frequent_illnesses, hearing_problems, high_fevers, hospitalization,
        rheumatic_fever, seizures_convulsions, serious_injuries_accidents, surgeries, vision_problems, medical_other, illness_during_pregnancy, condition_of_newborn,
        duration_of_pregnancy, birth_weight_lbs, birth_weight_oz, complications, bottle_fed, breast_fed, family_history_allergies, family_history_heart_problems,
family_history_tuberculosis, family_history_asthma, family_history_high_blood_pressure, family_history_vision_problems, family_history_diabetes,
family_history_hyperactivity, family_history_epilepsy, family_history_no_illness, other_siblings_name, other_siblings_age, age_group_friends, neighborhood_friends,
relationship_with_mother, relationship_with_father, relationship_with_siblings, relationship_with_extended_family, fears_conflicts, child_response_frustration,
favorite_activities, last_five_years_moved, things_used_at_home, hours_of_television_daily, language_used_at_home, changes_at_home_situation,
educational_expectations_of_child, other_important_family_members, about_family_celebrations, childcare_before, reason_for_childcare_before, what_child_interests,
drop_off_time, pick_up_time, restricted_diet, restricted_diet_reason, eat_own, eat_own_reason, favorite_foods, rest_in_the_middle_day, reason_for_rest_in_the_middle_day,
rest_routine, toilet_trained, reason_for_toilet_trained, existing_illness_allergy, explain_for_existing_illness_allergy, functioning_at_age, explain_for_functioning_at_age,
able_to_walk, explain_for_able_to_walk, communicate_their_needs, explain_for_communicate_their_needs, any_medication, explain_for_any_medication,
utilize_special_equipment, explain_for_utilize_special_equipment, significant_periods, explain_for_significant_periods, desire_any_accommodations,
explain_for_desire_any_accommodations, additional_information, agree_all_child_information_is_correct, agree_all_above_information_is_correct,
do_you_agree_this_immunization_instructions, do_you_agree_profile_information, child_password_pick_up_password_form, do_you_agree_this_pick_up_password_form,
photo_usage_photo_video_permission_form, photo_permission_agree_group_photos_electronic, do_you_agree_this_photo_video_permission_form, do_you_agree_this_security_release_policy_form,
contact_emergency_medical_technicians_medical_transportation_waiver, do_you_agree_this_medical_transportation_waiver, do_you_agree_this_health_policies,
outside_waiver_parent_sign_outside_engagements_waiver, approve_social_media_post, printed_name_social_media_post, do_you_agree_this_social_media_post, bank_routing,
bank_account, driver_license, state, myself, enrollment_name, point_one_field_three, point_two_initial_here, point_three_initial_here, point_four_initial_here,
point_five_initial_here, point_six_initial_here, point_seven_initial_here, point_eight_initial_here, point_nine_initial_here, point_ten_initial_here,
point_eleven_initial_here, point_twelve_initial_here, point_thirteen_initial_here, point_fourteen_initial_here, point_fifteen_initial_here, point_sixteen_initial_here,
point_seventeen_initial_here, point_eighteen_initial_here, preferred_start_date, preferred_schedule, full_day, half_day, welcome_goddard_agreement, mission_statement_agreement,
general_information_agreement, statement_of_confidentiality, parent_access_agreement, release_of_children_agreement, registration_fees_agreement, outside_engagements_agreement,
health_policies_agreement, medication_procedures_agreement, bring_to_school_agreement, rest_time_agreement, training_philosophy_agreement, affiliation_policy_agreement,
security_issue_agreement, expulsion_policy_agreement, addressing_individual_child_agreement, finalword_agreement
) VALUES (
p_parent_id, p_additional_parent_id, p_class_id, p_care_provider_id, p_dentist_id, p_child_first_name, p_child_last_name, p_nick_name, p_dob, p_primary_language,
p_school_age_child_school, p_do_relevant_custody_papers_apply, p_gender, p_special_disabilities, p_allergies_medication_reaction, p_additional_info, p_medication,
p_health_insurance, p_policy_number, p_obtaining_emergency_medical_care, p_administration_first_aid_procedures, p_physical_exam_last_date, p_dental_exam_last_date,
p_allergies, p_asthma, p_bleeding_problems, p_diabetes, p_epilepsy, p_frequent_ear_infections, p_frequent_illnesses, p_hearing_problems, p_high_fevers, p_hospitalization,
p_rheumatic_fever, p_seizures_convulsions, p_serious_injuries_accidents, p_surgeries, p_vision_problems, p_medical_other, p_illness_during_pregnancy, p_condition_of_newborn,
p_duration_of_pregnancy, p_birth_weight_lbs, p_birth_weight_oz, p_complications, p_bottle_fed, p_breast_fed, p_family_history_allergies, p_family_history_heart_problems,
p_family_history_tuberculosis, p_family_history_asthma, p_family_history_high_blood_pressure, p_family_history_vision_problems, p_family_history_diabetes,
p_family_history_hyperactivity, p_family_history_epilepsy, p_family_history_no_illness, p_other_siblings_name, p_other_siblings_age, p_age_group_friends, p_neighborhood_friends,
p_relationship_with_mother, p_relationship_with_father, p_relationship_with_siblings, p_relationship_with_extended_family, p_fears_conflicts, p_child_response_frustration,
p_favorite_activities, p_last_five_years_moved, p_things_used_at_home, p_hours_of_television_daily, p_language_used_at_home, p_changes_at_home_situation,
p_educational_expectations_of_child, p_other_important_family_members, p_about_family_celebrations, p_childcare_before, p_reason_for_childcare_before, p_what_child_interests,
p_drop_off_time, p_pick_up_time, p_restricted_diet, p_restricted_diet_reason, p_eat_own, p_eat_own_reason, p_favorite_foods, p_rest_in_the_middle_day, p_reason_for_rest_in_the_middle_day,
p_rest_routine, p_toilet_trained, p_reason_for_toilet_trained, p_existing_illness_allergy, p_explain_for_existing_illness_allergy, p_functioning_at_age, p_explain_for_functioning_at_age,
p_able_to_walk, p_explain_for_able_to_walk, p_communicate_their_needs, p_explain_for_communicate_their_needs, p_any_medication, p_explain_for_any_medication,
p_utilize_special_equipment, p_explain_for_utilize_special_equipment, p_significant_periods, p_explain_for_significant_periods, p_desire_any_accommodations,
p_explain_for_desire_any_accommodations, p_additional_information, p_agree_all_child_information_is_correct, p_agree_all_above_information_is_correct,
p_do_you_agree_this_immunization_instructions, p_do_you_agree_profile_information, p_child_password_pick_up_password_form, p_do_you_agree_this_pick_up_password_form,
p_photo_usage_photo_video_permission_form, p_photo_permission_agree_group_photos_electronic, p_do_you_agree_this_photo_video_permission_form, p_do_you_agree_this_security_release_policy_form,
p_contact_emergency_medical_technicians_medical_transportation_waiver, p_do_you_agree_this_medical_transportation_waiver, p_do_you_agree_this_health_policies,
p_outside_waiver_parent_sign_outside_engagements_waiver, p_approve_social_media_post, p_printed_name_social_media_post, p_do_you_agree_this_social_media_post, p_bank_routing,
p_bank_account, p_driver_license, p_state, p_myself, p_enrollment_name, p_point_one_field_three, p_point_two_initial_here, p_point_three_initial_here, p_point_four_initial_here,
p_point_five_initial_here, p_point_six_initial_here, p_point_seven_initial_here, p_point_eight_initial_here, p_point_nine_initial_here, p_point_ten_initial_here,
p_point_eleven_initial_here, p_point_twelve_initial_here, p_point_thirteen_initial_here, p_point_fourteen_initial_here, p_point_fifteen_initial_here, p_point_sixteen_initial_here,
p_point_seventeen_initial_here, p_point_eighteen_initial_here, p_preferred_start_date, p_preferred_schedule, p_full_day, p_half_day, p_welcome_goddard_agreement, p_mission_statement_agreement,
p_general_information_agreement, p_statement_of_confidentiality, p_parent_access_agreement, p_release_of_children_agreement, p_registration_fees_agreement, p_outside_engagements_agreement,
p_health_policies_agreement, p_medication_procedures_agreement, p_bring_to_school_agreement, p_rest_time_agreement, p_training_philosophy_agreement, p_affiliation_policy_agreement,
p_security_issue_agreement, p_expulsion_policy_agreement, p_addressing_individual_child_agreement, p_finalword_agreement
);
END$$

DELIMITER ;



DELIMITER $$

CREATE PROCEDURE `ReadChildInfo`(
    IN p_child_id INT
)
BEGIN
    SELECT * FROM child_info WHERE child_id = p_child_id;
END$$

DELIMITER ;